// ───────────────────────────────────────────────────────────
// SƠ CẤP 1 — 10 bài, trích từ 10 file PDF (1,3,5,...,19.pdf)
// Thứ tự bài theo thứ tự file người dùng yêu cầu (1 -> 19).
//
// Mỗi bài import 3 loại bài tập tái dùng engine sẵn có:
//   translation         : Gõ từ vựng / Dịch nghĩa (sinh từ 生词)
//   sentenceTranslation : Dịch câu (Việt -> Trung, có đáp án rõ)
//   sentence            : Sắp xếp câu (chuỗi Hán liền, chấm bằng split(''))
//
// Bỏ qua: bài điền chỗ trống, đọc số, viết đoạn văn tự luận
// (không có đáp án đơn nhất để chấm tự động).
// ───────────────────────────────────────────────────────────

export const LESSONS = [
  // ═══════════ BÀI 1 (file 1.pdf) · 数字 Số đếm ═══════════
  {
    name: "Bài 1 · Số đếm 数字",
    translation: [
      { chinese: "零", pinyin: "líng", vietnamese: "không (số 0)", wordType: "Số từ" },
      { chinese: "一", pinyin: "yī", vietnamese: "một", wordType: "Số từ" },
      { chinese: "二", pinyin: "èr", vietnamese: "hai", wordType: "Số từ" },
      { chinese: "三", pinyin: "sān", vietnamese: "ba", wordType: "Số từ" },
      { chinese: "四", pinyin: "sì", vietnamese: "bốn", wordType: "Số từ" },
      { chinese: "五", pinyin: "wǔ", vietnamese: "năm", wordType: "Số từ" },
      { chinese: "六", pinyin: "liù", vietnamese: "sáu", wordType: "Số từ" },
      { chinese: "七", pinyin: "qī", vietnamese: "bảy", wordType: "Số từ" },
      { chinese: "八", pinyin: "bā", vietnamese: "tám", wordType: "Số từ" },
      { chinese: "九", pinyin: "jiǔ", vietnamese: "chín", wordType: "Số từ" },
      { chinese: "十", pinyin: "shí", vietnamese: "mười", wordType: "Số từ" },
      { chinese: "百", pinyin: "bǎi", vietnamese: "trăm", wordType: "Số từ" },
      { chinese: "千", pinyin: "qiān", vietnamese: "nghìn", wordType: "Số từ" },
      { chinese: "万", pinyin: "wàn", vietnamese: "vạn (chục nghìn)", wordType: "Số từ" },
      { chinese: "两", pinyin: "liǎng", vietnamese: "hai (số lượng)", wordType: "Số từ" },
      { chinese: "亿", pinyin: "yì", vietnamese: "trăm triệu", wordType: "Số từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Hai cái điện thoại.", chineseSentence: "两个手机。", pinyin: "liǎng ge shǒujī." },
      { vietnameseSentence: "Ba người chúng tôi.", chineseSentence: "我们三个人。", pinyin: "wǒmen sān ge rén." },
      { vietnameseSentence: "Hai đứa chúng tôi.", chineseSentence: "我们俩。", pinyin: "wǒmen liǎ." },
    ],
    sentence: [],
  },

  // ═══════════ BÀI 2 (file 3.pdf) · 人称代词 Đại từ nhân xưng ═══════════
  {
    name: "Bài 2 · Đại từ nhân xưng 人称代词",
    translation: [
      { chinese: "我", pinyin: "wǒ", vietnamese: "tôi, tớ", wordType: "Đại từ" },
      { chinese: "你", pinyin: "nǐ", vietnamese: "bạn, cậu", wordType: "Đại từ" },
      { chinese: "他", pinyin: "tā", vietnamese: "anh ấy", wordType: "Đại từ" },
      { chinese: "她", pinyin: "tā", vietnamese: "cô ấy", wordType: "Đại từ" },
      { chinese: "它", pinyin: "tā", vietnamese: "nó (đồ vật, động vật)", wordType: "Đại từ" },
      { chinese: "您", pinyin: "nín", vietnamese: "ngài, ông, bà (tôn kính)", wordType: "Đại từ" },
      { chinese: "我们", pinyin: "wǒmen", vietnamese: "chúng tôi", wordType: "Đại từ" },
      { chinese: "你们", pinyin: "nǐmen", vietnamese: "các bạn", wordType: "Đại từ" },
      { chinese: "他们", pinyin: "tāmen", vietnamese: "họ (nam/chung)", wordType: "Đại từ" },
      { chinese: "她们", pinyin: "tāmen", vietnamese: "họ (nữ)", wordType: "Đại từ" },
      { chinese: "它们", pinyin: "tāmen", vietnamese: "chúng (vật)", wordType: "Đại từ" },
      { chinese: "大家", pinyin: "dàjiā", vietnamese: "mọi người", wordType: "Đại từ" },
      { chinese: "咱们", pinyin: "zánmen", vietnamese: "chúng ta", wordType: "Đại từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Tôi ăn cơm.", chineseSentence: "我吃饭。", pinyin: "wǒ chī fàn." },
      { vietnameseSentence: "Anh ấy học tiếng Trung.", chineseSentence: "他学中文。", pinyin: "tā xué zhōngwén." },
      { vietnameseSentence: "Hôm qua tôi đi học tiếng Trung.", chineseSentence: "昨天我去学中文。", pinyin: "zuótiān wǒ qù xué zhōngwén." },
      { vietnameseSentence: "Cô ấy rất xinh.", chineseSentence: "她很漂亮。", pinyin: "tā hěn piàoliang." },
      { vietnameseSentence: "Hôm nay tôi bận.", chineseSentence: "今天我忙。", pinyin: "jīntiān wǒ máng." },
      { vietnameseSentence: "Tôi là người Việt Nam.", chineseSentence: "我是越南人。", pinyin: "wǒ shì yuènán rén." },
      { vietnameseSentence: "Anh ấy là người tốt.", chineseSentence: "他是好人。", pinyin: "tā shì hǎo rén." },
      { vietnameseSentence: "Em ấy là cô gái xinh đẹp.", chineseSentence: "她是漂亮的姑娘。", pinyin: "tā shì piàoliang de gūniang." },
    ],
    sentence: [
      { correctSentence: "这是食堂", pinyin: "zhè shì shítáng", vietnameseMeaning: "Đây là nhà ăn." },
      { correctSentence: "我喝咖啡", pinyin: "wǒ hē kāfēi", vietnameseMeaning: "Tôi uống cà phê." },
      { correctSentence: "手机很好看", pinyin: "shǒujī hěn hǎokàn", vietnameseMeaning: "Điện thoại rất đẹp." },
      { correctSentence: "她很可爱", pinyin: "tā hěn kě'ài", vietnameseMeaning: "Cô ấy rất đáng yêu." },
      { correctSentence: "她是中文老师", pinyin: "tā shì zhōngwén lǎoshī", vietnameseMeaning: "Cô ấy là giáo viên tiếng Trung." },
      { correctSentence: "他是王经理", pinyin: "tā shì wáng jīnglǐ", vietnameseMeaning: "Anh ấy là giám đốc Vương." },
      { correctSentence: "我喜欢吃中国菜", pinyin: "wǒ xǐhuan chī zhōngguó cài", vietnameseMeaning: "Tôi thích ăn món Trung Quốc." },
      { correctSentence: "他是谦虚的人", pinyin: "tā shì qiānxū de rén", vietnameseMeaning: "Anh ấy là người khiêm tốn." },
    ],
  },

  // ═══════════ BÀI 3 (file 5.pdf) · 你好！Xin chào ═══════════
  {
    name: "Bài 3 · 你好！Xin chào",
    translation: [
      { chinese: "好", pinyin: "hǎo", vietnamese: "tốt, khỏe", wordType: "Tính từ" },
      { chinese: "很", pinyin: "hěn", vietnamese: "rất", wordType: "Phó từ" },
      { chinese: "经理", pinyin: "jīnglǐ", vietnamese: "giám đốc", wordType: "Danh từ" },
      { chinese: "老师", pinyin: "lǎoshī", vietnamese: "thầy/cô giáo", wordType: "Danh từ" },
      { chinese: "学生", pinyin: "xuésheng", vietnamese: "học sinh", wordType: "Danh từ" },
      { chinese: "不", pinyin: "bù", vietnamese: "không", wordType: "Phó từ" },
      { chinese: "是", pinyin: "shì", vietnamese: "là, phải", wordType: "Động từ" },
      { chinese: "好久不见", pinyin: "hǎojiǔ bújiàn", vietnamese: "đã lâu không gặp", wordType: "Cụm từ" },
      { chinese: "最近", pinyin: "zuìjìn", vietnamese: "gần đây", wordType: "Danh từ" },
      { chinese: "的", pinyin: "de", vietnamese: "của (trợ từ)", wordType: "Trợ từ" },
      { chinese: "身体", pinyin: "shēntǐ", vietnamese: "sức khỏe, cơ thể", wordType: "Danh từ" },
      { chinese: "工作", pinyin: "gōngzuò", vietnamese: "công việc, làm việc", wordType: "Danh/Động từ" },
      { chinese: "忙", pinyin: "máng", vietnamese: "bận", wordType: "Tính từ" },
      { chinese: "吗", pinyin: "ma", vietnamese: "(trợ từ nghi vấn)", wordType: "Trợ từ" },
      { chinese: "喜欢", pinyin: "xǐhuan", vietnamese: "thích", wordType: "Động từ" },
      { chinese: "吃", pinyin: "chī", vietnamese: "ăn", wordType: "Động từ" },
      { chinese: "水果", pinyin: "shuǐguǒ", vietnamese: "hoa quả", wordType: "Danh từ" },
      { chinese: "钱", pinyin: "qián", vietnamese: "tiền", wordType: "Danh từ" },
      { chinese: "呢", pinyin: "ne", vietnamese: "còn... thì sao", wordType: "Trợ từ" },
      { chinese: "也", pinyin: "yě", vietnamese: "cũng", wordType: "Phó từ" },
      { chinese: "谢谢", pinyin: "xièxie", vietnamese: "cảm ơn", wordType: "Động từ" },
      { chinese: "不客气", pinyin: "bú kèqi", vietnamese: "đừng khách sáo", wordType: "Cụm từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Tôi khỏe.", chineseSentence: "我好。", pinyin: "wǒ hǎo." },
      { vietnameseSentence: "Người tốt.", chineseSentence: "好人。", pinyin: "hǎo rén." },
      { vietnameseSentence: "Tôi rất tốt.", chineseSentence: "我很好。", pinyin: "wǒ hěn hǎo." },
      { vietnameseSentence: "Gần đây tôi rất khỏe.", chineseSentence: "最近我很好。", pinyin: "zuìjìn wǒ hěn hǎo." },
      { vietnameseSentence: "Điện thoại của tôi.", chineseSentence: "我的手机。", pinyin: "wǒ de shǒujī." },
      { vietnameseSentence: "Sức khỏe của tôi rất tốt.", chineseSentence: "我的身体很好。", pinyin: "wǒ de shēntǐ hěn hǎo." },
      { vietnameseSentence: "Công việc của tôi rất bận.", chineseSentence: "我的工作很忙。", pinyin: "wǒ de gōngzuò hěn máng." },
      { vietnameseSentence: "Bạn là thầy giáo phải không?", chineseSentence: "你是老师吗？", pinyin: "nǐ shì lǎoshī ma?" },
      { vietnameseSentence: "Bạn bận không?", chineseSentence: "你忙吗？", pinyin: "nǐ máng ma?" },
      { vietnameseSentence: "Tôi rất thích anh ấy.", chineseSentence: "我很喜欢他。", pinyin: "wǒ hěn xǐhuan tā." },
      { vietnameseSentence: "Tôi rất thích tiền.", chineseSentence: "我很喜欢钱。", pinyin: "wǒ hěn xǐhuan qián." },
      { vietnameseSentence: "Tôi là giáo viên, cô ấy cũng là giáo viên.", chineseSentence: "我是老师，她也是老师。", pinyin: "wǒ shì lǎoshī, tā yě shì lǎoshī." },
      { vietnameseSentence: "Đã lâu không gặp, dạo này bạn khỏe không?", chineseSentence: "好久不见，最近你好吗？", pinyin: "hǎojiǔ bújiàn, zuìjìn nǐ hǎo ma?" },
      { vietnameseSentence: "Bạn thích ăn hoa quả không?", chineseSentence: "你喜欢吃水果吗？", pinyin: "nǐ xǐhuan chī shuǐguǒ ma?" },
    ],
    sentence: [
      { correctSentence: "最近你好吗", pinyin: "zuìjìn nǐ hǎo ma", vietnameseMeaning: "Gần đây bạn khỏe không?" },
      { correctSentence: "我最近很好", pinyin: "wǒ zuìjìn hěn hǎo", vietnameseMeaning: "Gần đây tôi rất khỏe." },
      { correctSentence: "她是老师吗", pinyin: "tā shì lǎoshī ma", vietnameseMeaning: "Cô ấy là giáo viên à?" },
      { correctSentence: "我的工作不忙", pinyin: "wǒ de gōngzuò bù máng", vietnameseMeaning: "Công việc của tôi không bận." },
      { correctSentence: "你吃水果吗", pinyin: "nǐ chī shuǐguǒ ma", vietnameseMeaning: "Bạn ăn hoa quả không?" },
      { correctSentence: "我的身体不好", pinyin: "wǒ de shēntǐ bù hǎo", vietnameseMeaning: "Sức khỏe của tôi không tốt." },
      { correctSentence: "我很喜欢钱", pinyin: "wǒ hěn xǐhuan qián", vietnameseMeaning: "Tôi rất thích tiền." },
      { correctSentence: "她是好人", pinyin: "tā shì hǎo rén", vietnameseMeaning: "Cô ấy là người tốt." },
    ],
  },

  // ═══════════ BÀI 4 (file 7.pdf) · 你是哪国人？═══════════
  {
    name: "Bài 4 · 你是哪国人？",
    translation: [
      { chinese: "国", pinyin: "guó", vietnamese: "đất nước, quốc gia", wordType: "Danh từ" },
      { chinese: "哪", pinyin: "nǎ", vietnamese: "nào", wordType: "Đại từ" },
      { chinese: "这", pinyin: "zhè", vietnamese: "này, đây", wordType: "Đại từ" },
      { chinese: "那", pinyin: "nà", vietnamese: "kia, đó", wordType: "Đại từ" },
      { chinese: "越南", pinyin: "yuènán", vietnamese: "Việt Nam", wordType: "Danh từ" },
      { chinese: "中国", pinyin: "zhōngguó", vietnamese: "Trung Quốc", wordType: "Danh từ" },
      { chinese: "都", pinyin: "dōu", vietnamese: "đều", wordType: "Phó từ" },
      { chinese: "姓", pinyin: "xìng", vietnamese: "họ", wordType: "Danh/Động từ" },
      { chinese: "名字", pinyin: "míngzi", vietnamese: "tên", wordType: "Danh từ" },
      { chinese: "什么", pinyin: "shénme", vietnamese: "gì, cái gì", wordType: "Đại từ" },
      { chinese: "叫", pinyin: "jiào", vietnamese: "gọi, tên là", wordType: "Động từ" },
      { chinese: "请", pinyin: "qǐng", vietnamese: "xin, mời, hãy", wordType: "Động từ" },
      { chinese: "问", pinyin: "wèn", vietnamese: "hỏi", wordType: "Động từ" },
      { chinese: "进", pinyin: "jìn", vietnamese: "vào", wordType: "Động từ" },
      { chinese: "坐", pinyin: "zuò", vietnamese: "ngồi", wordType: "Động từ" },
      { chinese: "喝", pinyin: "hē", vietnamese: "uống", wordType: "Động từ" },
      { chinese: "茶", pinyin: "chá", vietnamese: "trà", wordType: "Danh từ" },
      { chinese: "咖啡", pinyin: "kāfēi", vietnamese: "cà phê", wordType: "Danh từ" },
      { chinese: "还是", pinyin: "háishi", vietnamese: "hay là", wordType: "Liên từ" },
      { chinese: "太", pinyin: "tài", vietnamese: "quá, lắm", wordType: "Phó từ" },
      { chinese: "了", pinyin: "le", vietnamese: "rồi", wordType: "Trợ từ" },
      { chinese: "吧", pinyin: "ba", vietnamese: "thôi, nhé, đi", wordType: "Trợ từ" },
      { chinese: "认识", pinyin: "rènshi", vietnamese: "quen biết", wordType: "Động từ" },
      { chinese: "高兴", pinyin: "gāoxìng", vietnamese: "vui, vui vẻ", wordType: "Tính từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Bạn là người nước nào?", chineseSentence: "你是哪国人？", pinyin: "nǐ shì nǎ guó rén?" },
      { vietnameseSentence: "Người này là cô giáo của tôi.", chineseSentence: "这个人是我的老师。", pinyin: "zhège rén shì wǒ de lǎoshī." },
      { vietnameseSentence: "Chúng tôi đều là người Việt Nam.", chineseSentence: "我们都是越南人。", pinyin: "wǒmen dōu shì yuènán rén." },
      { vietnameseSentence: "Tôi họ Nguyễn.", chineseSentence: "我姓阮。", pinyin: "wǒ xìng ruǎn." },
      { vietnameseSentence: "Bạn tên là gì?", chineseSentence: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi?" },
      { vietnameseSentence: "Bạn có thể gọi tôi là Mã Lệ.", chineseSentence: "你可以叫我玛丽。", pinyin: "nǐ kěyǐ jiào wǒ mǎlì." },
      { vietnameseSentence: "Mời vào.", chineseSentence: "请进。", pinyin: "qǐng jìn." },
      { vietnameseSentence: "Mời ngồi.", chineseSentence: "请坐。", pinyin: "qǐng zuò." },
      { vietnameseSentence: "Bạn uống trà hay là uống cà phê?", chineseSentence: "你喝茶还是喝咖啡？", pinyin: "nǐ hē chá háishi hē kāfēi?" },
      { vietnameseSentence: "Tôi ăn cơm rồi.", chineseSentence: "我吃饭了。", pinyin: "wǒ chī fàn le." },
      { vietnameseSentence: "Công việc của anh ấy bận lắm.", chineseSentence: "他的工作太忙了。", pinyin: "tā de gōngzuò tài máng le." },
      { vietnameseSentence: "Bạn quen người Trung Quốc không?", chineseSentence: "你认识中国人吗？", pinyin: "nǐ rènshi zhōngguó rén ma?" },
      { vietnameseSentence: "Rất vui được quen bạn.", chineseSentence: "很高兴认识你。", pinyin: "hěn gāoxìng rènshi nǐ." },
      { vietnameseSentence: "Bạn là người Việt Nam phải không?", chineseSentence: "你是不是越南人？", pinyin: "nǐ shì bu shì yuènán rén?" },
    ],
    sentence: [
      { correctSentence: "我们都是越南人", pinyin: "wǒmen dōu shì yuènán rén", vietnameseMeaning: "Chúng tôi đều là người Việt Nam." },
      { correctSentence: "他是英国人还是美国人", pinyin: "tā shì yīngguó rén háishi měiguó rén", vietnameseMeaning: "Anh ấy là người Anh hay người Mỹ?" },
      { correctSentence: "这是我的老师", pinyin: "zhè shì wǒ de lǎoshī", vietnameseMeaning: "Đây là cô giáo của tôi." },
      { correctSentence: "我认识一个中国人", pinyin: "wǒ rènshi yí ge zhōngguó rén", vietnameseMeaning: "Tôi quen một người Trung Quốc." },
      { correctSentence: "我的工作不太忙", pinyin: "wǒ de gōngzuò bú tài máng", vietnameseMeaning: "Công việc của tôi không bận lắm." },
      { correctSentence: "你喝咖啡吧", pinyin: "nǐ hē kāfēi ba", vietnameseMeaning: "Bạn uống cà phê nhé?" },
    ],
  },

  // ═══════════ BÀI 5 (file 9.pdf) · 汉语不太难 ═══════════
  {
    name: "Bài 5 · 汉语不太难",
    translation: [
      { chinese: "学", pinyin: "xué", vietnamese: "học", wordType: "Động từ" },
      { chinese: "学习", pinyin: "xuéxí", vietnamese: "học tập, việc học", wordType: "Động/Danh từ" },
      { chinese: "越南语", pinyin: "yuènányǔ", vietnamese: "tiếng Việt", wordType: "Danh từ" },
      { chinese: "汉语", pinyin: "hànyǔ", vietnamese: "tiếng Hán", wordType: "Danh từ" },
      { chinese: "英语", pinyin: "yīngyǔ", vietnamese: "tiếng Anh", wordType: "Danh từ" },
      { chinese: "要", pinyin: "yào", vietnamese: "muốn, cần, phải", wordType: "Động từ" },
      { chinese: "上课", pinyin: "shàng kè", vietnamese: "lên lớp, đi học", wordType: "Động từ" },
      { chinese: "下课", pinyin: "xià kè", vietnamese: "tan học", wordType: "Động từ" },
      { chinese: "会", pinyin: "huì", vietnamese: "biết (kỹ năng)", wordType: "Động từ" },
      { chinese: "去", pinyin: "qù", vietnamese: "đi", wordType: "Động từ" },
      { chinese: "学校", pinyin: "xuéxiào", vietnamese: "trường học", wordType: "Danh từ" },
      { chinese: "公司", pinyin: "gōngsī", vietnamese: "công ty", wordType: "Danh từ" },
      { chinese: "哪儿", pinyin: "nǎr", vietnamese: "đâu, chỗ nào", wordType: "Đại từ" },
      { chinese: "觉得", pinyin: "juéde", vietnamese: "cảm thấy", wordType: "Động từ" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", vietnamese: "như thế nào", wordType: "Đại từ" },
      { chinese: "难", pinyin: "nán", vietnamese: "khó", wordType: "Tính từ" },
      { chinese: "容易", pinyin: "róngyì", vietnamese: "dễ dàng", wordType: "Tính từ" },
      { chinese: "听", pinyin: "tīng", vietnamese: "nghe", wordType: "Động từ" },
      { chinese: "看", pinyin: "kàn", vietnamese: "xem, nhìn, đọc", wordType: "Động từ" },
      { chinese: "说", pinyin: "shuō", vietnamese: "nói", wordType: "Động từ" },
      { chinese: "和", pinyin: "hé", vietnamese: "và, với", wordType: "Liên từ" },
      { chinese: "比较", pinyin: "bǐjiào", vietnamese: "tương đối, khá", wordType: "Phó từ" },
      { chinese: "但是", pinyin: "dànshì", vietnamese: "nhưng", wordType: "Liên từ" },
      { chinese: "汉字", pinyin: "hànzì", vietnamese: "chữ Hán", wordType: "Danh từ" },
      { chinese: "发音", pinyin: "fāyīn", vietnamese: "phát âm", wordType: "Danh/Động từ" },
      { chinese: "写", pinyin: "xiě", vietnamese: "viết", wordType: "Động từ" },
      { chinese: "打", pinyin: "dǎ", vietnamese: "gõ, đánh", wordType: "Động từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Bạn học cái gì?", chineseSentence: "你学什么？", pinyin: "nǐ xué shénme?" },
      { vietnameseSentence: "Tôi thích học tiếng Trung.", chineseSentence: "我喜欢学汉语。", pinyin: "wǒ xǐhuan xué hànyǔ." },
      { vietnameseSentence: "Tôi muốn học tiếng Trung.", chineseSentence: "我要学习中文。", pinyin: "wǒ yào xuéxí zhōngwén." },
      { vietnameseSentence: "Bạn biết tiếng Trung không?", chineseSentence: "你会中文吗？", pinyin: "nǐ huì zhōngwén ma?" },
      { vietnameseSentence: "Tôi đi đến trường học tiếng Trung.", chineseSentence: "我去学校学中文。", pinyin: "wǒ qù xuéxiào xué zhōngwén." },
      { vietnameseSentence: "Bạn đi đâu ăn cơm?", chineseSentence: "你去哪儿吃饭？", pinyin: "nǐ qù nǎr chī fàn?" },
      { vietnameseSentence: "Bạn cảm thấy tiếng Trung khó không?", chineseSentence: "你觉得汉语难吗？", pinyin: "nǐ juéde hànyǔ nán ma?" },
      { vietnameseSentence: "Tiếng Trung không khó lắm.", chineseSentence: "汉语不太难。", pinyin: "hànyǔ bú tài nán." },
      { vietnameseSentence: "Gần đây bạn học tập như thế nào?", chineseSentence: "最近你学习怎么样？", pinyin: "zuìjìn nǐ xuéxí zěnmeyàng?" },
      { vietnameseSentence: "Tôi không biết viết chữ Hán, nhưng tôi biết gõ.", chineseSentence: "我不会写汉字，但是我会打。", pinyin: "wǒ bú huì xiě hànzì, dànshì wǒ huì dǎ." },
      { vietnameseSentence: "Tôi biết nói tiếng Trung.", chineseSentence: "我会说中文。", pinyin: "wǒ huì shuō zhōngwén." },
      { vietnameseSentence: "Bạn học tiếng Anh hay tiếng Trung?", chineseSentence: "你学英语还是中文？", pinyin: "nǐ xué yīngyǔ háishi zhōngwén?" },
      { vietnameseSentence: "Tôi không phải đi học.", chineseSentence: "我不要上课。", pinyin: "wǒ bú yào shàng kè." },
      { vietnameseSentence: "Anh ấy là người mà tôi yêu.", chineseSentence: "他是我爱的人。", pinyin: "tā shì wǒ ài de rén." },
    ],
    sentence: [
      { correctSentence: "我不学习汉语", pinyin: "wǒ bù xuéxí hànyǔ", vietnameseMeaning: "Tôi không học tiếng Hán." },
      { correctSentence: "你喜欢学英语吗", pinyin: "nǐ xǐhuan xué yīngyǔ ma", vietnameseMeaning: "Bạn thích học tiếng Anh không?" },
      { correctSentence: "他在中国工作", pinyin: "tā zài zhōngguó gōngzuò", vietnameseMeaning: "Anh ấy làm việc ở Trung Quốc." },
      { correctSentence: "我会写汉字", pinyin: "wǒ huì xiě hànzì", vietnameseMeaning: "Tôi biết viết chữ Hán." },
      { correctSentence: "我不要上课", pinyin: "wǒ bú yào shàng kè", vietnameseMeaning: "Tôi không phải đi học." },
      { correctSentence: "他是汉语老师", pinyin: "tā shì hànyǔ lǎoshī", vietnameseMeaning: "Anh ấy là giáo viên tiếng Hán." },
    ],
  },

  // ═══════════ BÀI 6 (file 11.pdf) · 你家有几口人？═══════════
  {
    name: "Bài 6 · 你家有几口人？",
    translation: [
      { chinese: "家", pinyin: "jiā", vietnamese: "nhà", wordType: "Danh từ" },
      { chinese: "在", pinyin: "zài", vietnamese: "ở, đang", wordType: "Động/Giới từ" },
      { chinese: "回", pinyin: "huí", vietnamese: "về", wordType: "Động từ" },
      { chinese: "有", pinyin: "yǒu", vietnamese: "có", wordType: "Động từ" },
      { chinese: "没有", pinyin: "méiyǒu", vietnamese: "không có", wordType: "Động từ" },
      { chinese: "几", pinyin: "jǐ", vietnamese: "mấy, vài", wordType: "Đại từ" },
      { chinese: "谁", pinyin: "shéi", vietnamese: "ai", wordType: "Đại từ" },
      { chinese: "爸爸", pinyin: "bàba", vietnamese: "bố", wordType: "Danh từ" },
      { chinese: "妈妈", pinyin: "māma", vietnamese: "mẹ", wordType: "Danh từ" },
      { chinese: "兄弟姐妹", pinyin: "xiōngdì jiěmèi", vietnamese: "anh chị em", wordType: "Danh từ" },
      { chinese: "哥哥", pinyin: "gēge", vietnamese: "anh trai", wordType: "Danh từ" },
      { chinese: "姐姐", pinyin: "jiějie", vietnamese: "chị gái", wordType: "Danh từ" },
      { chinese: "弟弟", pinyin: "dìdi", vietnamese: "em trai", wordType: "Danh từ" },
      { chinese: "妹妹", pinyin: "mèimei", vietnamese: "em gái", wordType: "Danh từ" },
      { chinese: "已经", pinyin: "yǐjīng", vietnamese: "đã", wordType: "Phó từ" },
      { chinese: "结婚", pinyin: "jiéhūn", vietnamese: "kết hôn", wordType: "Động từ" },
      { chinese: "老公", pinyin: "lǎogōng", vietnamese: "chồng", wordType: "Danh từ" },
      { chinese: "老婆", pinyin: "lǎopó", vietnamese: "vợ", wordType: "Danh từ" },
      { chinese: "孩子", pinyin: "háizi", vietnamese: "con cái", wordType: "Danh từ" },
      { chinese: "朋友", pinyin: "péngyou", vietnamese: "bạn bè", wordType: "Danh từ" },
      { chinese: "漂亮", pinyin: "piàoliang", vietnamese: "xinh đẹp", wordType: "Tính từ" },
      { chinese: "帅", pinyin: "shuài", vietnamese: "đẹp trai", wordType: "Tính từ" },
      { chinese: "对不起", pinyin: "duìbuqǐ", vietnamese: "xin lỗi", wordType: "Cụm từ" },
      { chinese: "没关系", pinyin: "méi guānxi", vietnamese: "không có gì", wordType: "Cụm từ" },
      { chinese: "还", pinyin: "hái", vietnamese: "vẫn, còn", wordType: "Phó từ" },
      { chinese: "单身", pinyin: "dānshēn", vietnamese: "độc thân", wordType: "Tính từ" },
      { chinese: "可爱", pinyin: "kě'ài", vietnamese: "đáng yêu", wordType: "Tính từ" },
      { chinese: "女儿", pinyin: "nǚ'ér", vietnamese: "con gái", wordType: "Danh từ" },
      { chinese: "儿子", pinyin: "érzi", vietnamese: "con trai", wordType: "Danh từ" },
      { chinese: "关系", pinyin: "guānxì", vietnamese: "quan hệ", wordType: "Danh từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Nhà của tôi rất to.", chineseSentence: "我的家很大。", pinyin: "wǒ de jiā hěn dà." },
      { vietnameseSentence: "Bắc Ninh là quê tôi.", chineseSentence: "北宁是我的老家。", pinyin: "běiníng shì wǒ de lǎojiā." },
      { vietnameseSentence: "Bạn học tiếng Trung ở đâu?", chineseSentence: "你在哪儿学汉语？", pinyin: "nǐ zài nǎr xué hànyǔ?" },
      { vietnameseSentence: "Tôi đang học tiếng Trung.", chineseSentence: "我在学中文。", pinyin: "wǒ zài xué zhōngwén." },
      { vietnameseSentence: "Tôi có một cái điện thoại.", chineseSentence: "我有一个手机。", pinyin: "wǒ yǒu yí ge shǒujī." },
      { vietnameseSentence: "Tôi không có tiền.", chineseSentence: "我没有钱。", pinyin: "wǒ méiyǒu qián." },
      { vietnameseSentence: "Bạn có hoa quả không?", chineseSentence: "你有没有水果？", pinyin: "nǐ yǒu méiyǒu shuǐguǒ?" },
      { vietnameseSentence: "Tôi chưa ăn cơm.", chineseSentence: "我还没吃饭。", pinyin: "wǒ hái méi chī fàn." },
      { vietnameseSentence: "Cô giáo của bạn là ai?", chineseSentence: "你的老师是谁？", pinyin: "nǐ de lǎoshī shì shéi?" },
      { vietnameseSentence: "Nhà bạn có mấy anh chị em?", chineseSentence: "你家有几个兄弟姐妹？", pinyin: "nǐ jiā yǒu jǐ ge xiōngdì jiěmèi?" },
      { vietnameseSentence: "Anh ấy đã kết hôn rồi.", chineseSentence: "他已经结婚了。", pinyin: "tā yǐjīng jiéhūn le." },
      { vietnameseSentence: "Bạn có mấy đứa con?", chineseSentence: "你有几个孩子？", pinyin: "nǐ yǒu jǐ ge háizi?" },
      { vietnameseSentence: "Chúng tôi là bạn tốt.", chineseSentence: "我们是好朋友。", pinyin: "wǒmen shì hǎo péngyou." },
      { vietnameseSentence: "Quê tôi ở Quế Võ, Bắc Ninh.", chineseSentence: "我的老家在北宁桂武。", pinyin: "wǒ de lǎojiā zài běiníng guìwǔ." },
      { vietnameseSentence: "Anh trai của tôi vẫn chưa kết hôn.", chineseSentence: "我的哥哥还没结婚。", pinyin: "wǒ de gēge hái méi jiéhūn." },
    ],
    sentence: [
      { correctSentence: "我的家有六个人", pinyin: "wǒ de jiā yǒu liù ge rén", vietnameseMeaning: "Nhà tôi có sáu người." },
      { correctSentence: "你在哪儿学汉语", pinyin: "nǐ zài nǎr xué hànyǔ", vietnameseMeaning: "Bạn học tiếng Hán ở đâu?" },
      { correctSentence: "我的家有三个兄弟姐妹", pinyin: "wǒ de jiā yǒu sān ge xiōngdì jiěmèi", vietnameseMeaning: "Nhà tôi có ba anh chị em." },
      { correctSentence: "我的孩子很可爱", pinyin: "wǒ de háizi hěn kě'ài", vietnameseMeaning: "Con tôi rất đáng yêu." },
      { correctSentence: "我的弟弟还没结婚", pinyin: "wǒ de dìdi hái méi jiéhūn", vietnameseMeaning: "Em trai tôi vẫn chưa kết hôn." },
      { correctSentence: "你的女朋友是谁", pinyin: "nǐ de nǚ péngyou shì shéi", vietnameseMeaning: "Bạn gái bạn là ai?" },
      { correctSentence: "他的老婆是中国人", pinyin: "tā de lǎopó shì zhōngguó rén", vietnameseMeaning: "Vợ anh ấy là người Trung Quốc." },
      { correctSentence: "我们的关系很好", pinyin: "wǒmen de guānxì hěn hǎo", vietnameseMeaning: "Quan hệ của chúng tôi rất tốt." },
    ],
  },

  // ═══════════ BÀI 7 (file 13.pdf) · 自我介绍一下儿 Giới thiệu bản thân ═══════════
  {
    name: "Bài 7 · Giới thiệu bản thân 自我介绍",
    translation: [
      { chinese: "先", pinyin: "xiān", vietnamese: "trước tiên", wordType: "Phó từ" },
      { chinese: "介绍", pinyin: "jièshào", vietnamese: "giới thiệu", wordType: "Động từ" },
      { chinese: "一下儿", pinyin: "yíxiàr", vietnamese: "một chút", wordType: "Cụm từ" },
      { chinese: "岁", pinyin: "suì", vietnamese: "tuổi", wordType: "Lượng từ" },
      { chinese: "几岁", pinyin: "jǐ suì", vietnamese: "mấy tuổi", wordType: "Cụm từ" },
      { chinese: "多大", pinyin: "duō dà", vietnamese: "bao nhiêu tuổi", wordType: "Cụm từ" },
      { chinese: "住", pinyin: "zhù", vietnamese: "ở, sống", wordType: "Động từ" },
      { chinese: "来自", pinyin: "láizì", vietnamese: "đến từ", wordType: "Động từ" },
      { chinese: "远", pinyin: "yuǎn", vietnamese: "xa", wordType: "Tính từ" },
      { chinese: "近", pinyin: "jìn", vietnamese: "gần", wordType: "Tính từ" },
      { chinese: "做", pinyin: "zuò", vietnamese: "làm", wordType: "Động từ" },
      { chinese: "当", pinyin: "dāng", vietnamese: "làm (chức vụ)", wordType: "Động từ" },
      { chinese: "办公员", pinyin: "bàngōngyuán", vietnamese: "nhân viên văn phòng", wordType: "Danh từ" },
      { chinese: "最", pinyin: "zuì", vietnamese: "nhất", wordType: "Phó từ" },
      { chinese: "常常", pinyin: "chángcháng", vietnamese: "thường xuyên", wordType: "Phó từ" },
      { chinese: "爱好", pinyin: "àihào", vietnamese: "sở thích", wordType: "Danh từ" },
      { chinese: "旅游", pinyin: "lǚyóu", vietnamese: "du lịch", wordType: "Động từ" },
      { chinese: "看电影", pinyin: "kàn diànyǐng", vietnamese: "xem phim", wordType: "Cụm từ" },
      { chinese: "对", pinyin: "duì", vietnamese: "đúng", wordType: "Tính từ" },
      { chinese: "错", pinyin: "cuò", vietnamese: "sai", wordType: "Tính từ" },
      { chinese: "跟", pinyin: "gēn", vietnamese: "và, với", wordType: "Liên/Giới từ" },
      { chinese: "一起", pinyin: "yìqǐ", vietnamese: "cùng nhau", wordType: "Phó từ" },
      { chinese: "见面", pinyin: "jiànmiàn", vietnamese: "gặp mặt", wordType: "Động từ" },
      { chinese: "再见", pinyin: "zàijiàn", vietnamese: "tạm biệt", wordType: "Cụm từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Trước tiên tôi xin giới thiệu một chút.", chineseSentence: "我先介绍一下。", pinyin: "wǒ xiān jièshào yíxià." },
      { vietnameseSentence: "Đợi tôi một chút.", chineseSentence: "等我一下儿。", pinyin: "děng wǒ yíxiàr." },
      { vietnameseSentence: "Năm nay tôi 18 tuổi.", chineseSentence: "我今年十八岁。", pinyin: "wǒ jīnnián shíbā suì." },
      { vietnameseSentence: "Bạn sống ở đâu?", chineseSentence: "你住哪儿？", pinyin: "nǐ zhù nǎr?" },
      { vietnameseSentence: "Tôi đến từ Bắc Ninh.", chineseSentence: "我来自北宁。", pinyin: "wǒ láizì běiníng." },
      { vietnameseSentence: "Tôi làm giáo viên tiếng Hán.", chineseSentence: "我当汉语老师。", pinyin: "wǒ dāng hànyǔ lǎoshī." },
      { vietnameseSentence: "Bạn làm công việc gì?", chineseSentence: "你做什么工作？", pinyin: "nǐ zuò shénme gōngzuò?" },
      { vietnameseSentence: "Anh ấy là người tốt nhất.", chineseSentence: "他是最好的人。", pinyin: "tā shì zuì hǎo de rén." },
      { vietnameseSentence: "Bạn có sở thích gì?", chineseSentence: "你有什么爱好？", pinyin: "nǐ yǒu shénme àihào?" },
      { vietnameseSentence: "Bạn viết sai rồi.", chineseSentence: "你写错了。", pinyin: "nǐ xiě cuò le." },
      { vietnameseSentence: "Tôi cùng cô ấy học tiếng Trung.", chineseSentence: "我跟她一起学中文。", pinyin: "wǒ gēn tā yìqǐ xué zhōngwén." },
      { vietnameseSentence: "Cuối tuần này tôi gặp mặt bạn bè.", chineseSentence: "这周末我跟朋友见面。", pinyin: "zhè zhōumò wǒ gēn péngyou jiànmiàn." },
      { vietnameseSentence: "Từ nhà tôi đến công ty không xa lắm.", chineseSentence: "从我家到公司不太远。", pinyin: "cóng wǒ jiā dào gōngsī bú tài yuǎn." },
      { vietnameseSentence: "Tôi thường xuyên gặp mặt bạn bè.", chineseSentence: "我常常跟朋友见面。", pinyin: "wǒ chángcháng gēn péngyou jiànmiàn." },
    ],
    sentence: [
      { correctSentence: "你妹妹今年多大", pinyin: "nǐ mèimei jīnnián duō dà", vietnameseMeaning: "Năm nay em gái bạn bao nhiêu tuổi?" },
      { correctSentence: "你现在住在哪里", pinyin: "nǐ xiànzài zhù zài nǎlǐ", vietnameseMeaning: "Hiện tại bạn sống ở đâu?" },
      { correctSentence: "我的朋友来自中国", pinyin: "wǒ de péngyou láizì zhōngguó", vietnameseMeaning: "Bạn tôi đến từ Trung Quốc." },
      { correctSentence: "从我家到公司很近", pinyin: "cóng wǒ jiā dào gōngsī hěn jìn", vietnameseMeaning: "Từ nhà tôi đến công ty rất gần." },
      { correctSentence: "你爸妈做什么工作", pinyin: "nǐ bàmā zuò shénme gōngzuò", vietnameseMeaning: "Bố mẹ bạn làm công việc gì?" },
      { correctSentence: "你会做饭吗", pinyin: "nǐ huì zuò fàn ma", vietnameseMeaning: "Bạn biết nấu ăn không?" },
      { correctSentence: "我最喜欢去旅游", pinyin: "wǒ zuì xǐhuan qù lǚyóu", vietnameseMeaning: "Tôi thích đi du lịch nhất." },
      { correctSentence: "我常常听音乐和看电影", pinyin: "wǒ chángcháng tīng yīnyuè hé kàn diànyǐng", vietnameseMeaning: "Tôi thường nghe nhạc và xem phim." },
    ],
  },

  // ═══════════ BÀI 8 (file 15.pdf) · 明天见！Ngày mai gặp lại ═══════════
  {
    name: "Bài 8 · 明天见！Ngày mai gặp lại",
    translation: [
      { chinese: "有空儿", pinyin: "yǒu kòngr", vietnamese: "rảnh", wordType: "Cụm từ" },
      { chinese: "时间", pinyin: "shíjiān", vietnamese: "thời gian", wordType: "Danh từ" },
      { chinese: "什么时候", pinyin: "shénme shíhou", vietnamese: "khi nào, lúc nào", wordType: "Cụm từ" },
      { chinese: "每", pinyin: "měi", vietnamese: "mỗi, hàng", wordType: "Đại từ" },
      { chinese: "昨天", pinyin: "zuótiān", vietnamese: "hôm qua", wordType: "Danh từ" },
      { chinese: "今天", pinyin: "jīntiān", vietnamese: "hôm nay", wordType: "Danh từ" },
      { chinese: "明天", pinyin: "míngtiān", vietnamese: "ngày mai", wordType: "Danh từ" },
      { chinese: "早上", pinyin: "zǎoshang", vietnamese: "sáng sớm", wordType: "Danh từ" },
      { chinese: "上午", pinyin: "shàngwǔ", vietnamese: "buổi sáng", wordType: "Danh từ" },
      { chinese: "中午", pinyin: "zhōngwǔ", vietnamese: "buổi trưa", wordType: "Danh từ" },
      { chinese: "下午", pinyin: "xiàwǔ", vietnamese: "buổi chiều", wordType: "Danh từ" },
      { chinese: "晚上", pinyin: "wǎnshang", vietnamese: "buổi tối", wordType: "Danh từ" },
      { chinese: "星期", pinyin: "xīngqī", vietnamese: "tuần, thứ", wordType: "Danh từ" },
      { chinese: "星期几", pinyin: "xīngqī jǐ", vietnamese: "thứ mấy", wordType: "Cụm từ" },
      { chinese: "周末", pinyin: "zhōumò", vietnamese: "cuối tuần", wordType: "Danh từ" },
      { chinese: "年", pinyin: "nián", vietnamese: "năm", wordType: "Danh từ" },
      { chinese: "去年", pinyin: "qùnián", vietnamese: "năm ngoái", wordType: "Danh từ" },
      { chinese: "今年", pinyin: "jīnnián", vietnamese: "năm nay", wordType: "Danh từ" },
      { chinese: "明年", pinyin: "míngnián", vietnamese: "sang năm", wordType: "Danh từ" },
      { chinese: "出生", pinyin: "chūshēng", vietnamese: "sinh ra", wordType: "Động từ" },
      { chinese: "月", pinyin: "yuè", vietnamese: "tháng", wordType: "Danh từ" },
      { chinese: "号", pinyin: "hào", vietnamese: "ngày, mùng", wordType: "Danh từ" },
      { chinese: "上班", pinyin: "shàngbān", vietnamese: "đi làm", wordType: "Động từ" },
      { chinese: "下班", pinyin: "xiàbān", vietnamese: "tan làm", wordType: "Động từ" },
      { chinese: "加班", pinyin: "jiābān", vietnamese: "tăng ca", wordType: "Động từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Khi nào bạn rảnh?", chineseSentence: "你什么时候有空儿？", pinyin: "nǐ shénme shíhou yǒu kòngr?" },
      { vietnameseSentence: "Mỗi ngày tôi đều phải đi công ty làm việc.", chineseSentence: "每天我都要去公司工作。", pinyin: "měitiān wǒ dōu yào qù gōngsī gōngzuò." },
      { vietnameseSentence: "Sáng nay tôi không ăn cơm.", chineseSentence: "今天早上我不吃饭。", pinyin: "jīntiān zǎoshang wǒ bù chī fàn." },
      { vietnameseSentence: "Thứ mấy bạn phải đi học tiếng Trung?", chineseSentence: "你星期几要去学中文？", pinyin: "nǐ xīngqī jǐ yào qù xué zhōngwén?" },
      { vietnameseSentence: "Sang năm tôi kết hôn.", chineseSentence: "明年我结婚。", pinyin: "míngnián wǒ jiéhūn." },
      { vietnameseSentence: "Sinh nhật của bạn vào ngày mấy tháng mấy?", chineseSentence: "你的生日是几月几号？", pinyin: "nǐ de shēngrì shì jǐ yuè jǐ hào?" },
      { vietnameseSentence: "Hôm nay tôi không phải đi làm.", chineseSentence: "今天我不要去上班。", pinyin: "jīntiān wǒ bú yào qù shàngbān." },
      { vietnameseSentence: "Hôm nay tôi ăn cơm ở công ty.", chineseSentence: "今天我在公司吃饭。", pinyin: "jīntiān wǒ zài gōngsī chī fàn." },
      { vietnameseSentence: "Khi nào bạn có thời gian?", chineseSentence: "你什么时候有时间？", pinyin: "nǐ shénme shíhou yǒu shíjiān?" },
      { vietnameseSentence: "Cuối tuần này tôi gặp bạn bè tại Bắc Ninh.", chineseSentence: "这周末我跟朋友在北宁见面。", pinyin: "zhè zhōumò wǒ gēn péngyou zài běiníng jiànmiàn." },
      { vietnameseSentence: "Tôi học tiếng Trung ba tháng rồi.", chineseSentence: "我学中文三个月了。", pinyin: "wǒ xué zhōngwén sān ge yuè le." },
      { vietnameseSentence: "Mỗi cuối tuần tôi đều về nhà thăm bố mẹ.", chineseSentence: "每周末我都回家看爸妈。", pinyin: "měi zhōumò wǒ dōu huí jiā kàn bàmā." },
    ],
    sentence: [
      { correctSentence: "你什么时候有空儿", pinyin: "nǐ shénme shíhou yǒu kòngr", vietnameseMeaning: "Khi nào bạn rảnh?" },
      { correctSentence: "你星期几要去学中文", pinyin: "nǐ xīngqī jǐ yào qù xué zhōngwén", vietnameseMeaning: "Thứ mấy bạn phải đi học tiếng Trung?" },
      { correctSentence: "明年我结婚", pinyin: "míngnián wǒ jiéhūn", vietnameseMeaning: "Sang năm tôi kết hôn." },
      { correctSentence: "今天早上我不吃饭", pinyin: "jīntiān zǎoshang wǒ bù chī fàn", vietnameseMeaning: "Sáng nay tôi không ăn cơm." },
      { correctSentence: "我学中文三个月了", pinyin: "wǒ xué zhōngwén sān ge yuè le", vietnameseMeaning: "Tôi học tiếng Trung ba tháng rồi." },
    ],
  },

  // ═══════════ BÀI 9 (file 17.pdf) · 一斤苹果多少钱？═══════════
  {
    name: "Bài 9 · 一斤苹果多少钱？",
    translation: [
      { chinese: "买", pinyin: "mǎi", vietnamese: "mua", wordType: "Động từ" },
      { chinese: "卖", pinyin: "mài", vietnamese: "bán", wordType: "Động từ" },
      { chinese: "怎么", pinyin: "zěnme", vietnamese: "thế nào, kiểu gì", wordType: "Đại từ" },
      { chinese: "斤", pinyin: "jīn", vietnamese: "cân (0,5kg)", wordType: "Lượng từ" },
      { chinese: "公斤", pinyin: "gōngjīn", vietnamese: "cân, kg", wordType: "Lượng từ" },
      { chinese: "贵", pinyin: "guì", vietnamese: "đắt", wordType: "Tính từ" },
      { chinese: "便宜", pinyin: "piányi", vietnamese: "rẻ", wordType: "Tính từ" },
      { chinese: "一点儿", pinyin: "yìdiǎnr", vietnamese: "một chút", wordType: "Lượng từ" },
      { chinese: "有点儿", pinyin: "yǒudiǎnr", vietnamese: "hơi, có chút", wordType: "Phó từ" },
      { chinese: "多少", pinyin: "duōshao", vietnamese: "bao nhiêu", wordType: "Đại từ" },
      { chinese: "块", pinyin: "kuài", vietnamese: "đồng (tệ)", wordType: "Lượng từ" },
      { chinese: "毛", pinyin: "máo", vietnamese: "hào", wordType: "Lượng từ" },
      { chinese: "分", pinyin: "fēn", vietnamese: "xu", wordType: "Lượng từ" },
      { chinese: "橘子", pinyin: "júzi", vietnamese: "quýt", wordType: "Danh từ" },
      { chinese: "苹果", pinyin: "píngguǒ", vietnamese: "táo", wordType: "Danh từ" },
      { chinese: "别的", pinyin: "biéde", vietnamese: "cái khác", wordType: "Đại từ" },
      { chinese: "一共", pinyin: "yígòng", vietnamese: "tổng cộng", wordType: "Phó từ" },
      { chinese: "大概", pinyin: "dàgài", vietnamese: "khoảng, đại khái", wordType: "Phó từ" },
      { chinese: "找", pinyin: "zhǎo", vietnamese: "trả lại, tìm", wordType: "Động từ" },
      { chinese: "给", pinyin: "gěi", vietnamese: "cho", wordType: "Động/Giới từ" },
      { chinese: "种", pinyin: "zhǒng", vietnamese: "chủng, loại", wordType: "Lượng từ" },
      { chinese: "打折", pinyin: "dǎzhé", vietnamese: "giảm giá", wordType: "Động từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Cô ấy bán gì vậy?", chineseSentence: "她卖什么？", pinyin: "tā mài shénme?" },
      { vietnameseSentence: "Táo bán thế nào?", chineseSentence: "苹果怎么卖？", pinyin: "píngguǒ zěnme mài?" },
      { vietnameseSentence: "Sao bạn không ăn cơm?", chineseSentence: "你怎么不吃饭？", pinyin: "nǐ zěnme bù chī fàn?" },
      { vietnameseSentence: "Một cân táo bao nhiêu tiền?", chineseSentence: "苹果一斤多少钱？", pinyin: "píngguǒ yì jīn duōshao qián?" },
      { vietnameseSentence: "Bộ quần áo này đắt quá.", chineseSentence: "这件衣服太贵了。", pinyin: "zhè jiàn yīfu tài guì le." },
      { vietnameseSentence: "Bạn ăn một chút cơm đi.", chineseSentence: "你吃一点儿饭吧。", pinyin: "nǐ chī yìdiǎnr fàn ba." },
      { vietnameseSentence: "Tôi cảm thấy hơi mệt.", chineseSentence: "我觉得有点儿累。", pinyin: "wǒ juéde yǒudiǎnr lèi." },
      { vietnameseSentence: "Bạn có bao nhiêu tiền?", chineseSentence: "你有多少钱？", pinyin: "nǐ yǒu duōshao qián?" },
      { vietnameseSentence: "Tôi muốn mua một cân táo.", chineseSentence: "我想买一斤苹果。", pinyin: "wǒ xiǎng mǎi yì jīn píngguǒ." },
      { vietnameseSentence: "Bạn muốn mua cái khác không?", chineseSentence: "你想买别的吗？", pinyin: "nǐ xiǎng mǎi biéde ma?" },
      { vietnameseSentence: "Anh ấy cho tôi tiền.", chineseSentence: "他给我钱。", pinyin: "tā gěi wǒ qián." },
      { vietnameseSentence: "Anh ấy mua hoa quả cho tôi.", chineseSentence: "他给我买水果。", pinyin: "tā gěi wǒ mǎi shuǐguǒ." },
      { vietnameseSentence: "Loại này một cân bao nhiêu tiền?", chineseSentence: "这种一斤多少钱？", pinyin: "zhè zhǒng yì jīn duōshao qián?" },
      { vietnameseSentence: "Có thể rẻ hơn một chút không?", chineseSentence: "可以便宜一点儿吗？", pinyin: "kěyǐ piányi yìdiǎnr ma?" },
    ],
    sentence: [
      { correctSentence: "苹果一斤多少钱", pinyin: "píngguǒ yì jīn duōshao qián", vietnameseMeaning: "Một cân táo bao nhiêu tiền?" },
      { correctSentence: "这件衣服太贵了", pinyin: "zhè jiàn yīfu tài guì le", vietnameseMeaning: "Bộ quần áo này đắt quá." },
      { correctSentence: "你想买别的吗", pinyin: "nǐ xiǎng mǎi biéde ma", vietnameseMeaning: "Bạn muốn mua cái khác không?" },
      { correctSentence: "便宜一点儿吧", pinyin: "piányi yìdiǎnr ba", vietnameseMeaning: "Rẻ hơn một chút nhé." },
      { correctSentence: "他给我买水果", pinyin: "tā gěi wǒ mǎi shuǐguǒ", vietnameseMeaning: "Anh ấy mua hoa quả cho tôi." },
      { correctSentence: "我想买一斤苹果", pinyin: "wǒ xiǎng mǎi yì jīn píngguǒ", vietnameseMeaning: "Tôi muốn mua một cân táo." },
    ],
  },

  // ═══════════ BÀI 10 (file 19.pdf) · 你吃什么？═══════════
  {
    name: "Bài 10 · 你吃什么？",
    translation: [
      { chinese: "早", pinyin: "zǎo", vietnamese: "sớm", wordType: "Tính từ" },
      { chinese: "晚", pinyin: "wǎn", vietnamese: "muộn", wordType: "Tính từ" },
      { chinese: "早饭", pinyin: "zǎofàn", vietnamese: "bữa sáng", wordType: "Danh từ" },
      { chinese: "午饭", pinyin: "wǔfàn", vietnamese: "bữa trưa", wordType: "Danh từ" },
      { chinese: "晚饭", pinyin: "wǎnfàn", vietnamese: "bữa tối", wordType: "Danh từ" },
      { chinese: "饿", pinyin: "è", vietnamese: "đói", wordType: "Tính từ" },
      { chinese: "饱", pinyin: "bǎo", vietnamese: "no", wordType: "Tính từ" },
      { chinese: "饭", pinyin: "fàn", vietnamese: "cơm", wordType: "Danh từ" },
      { chinese: "碗", pinyin: "wǎn", vietnamese: "bát", wordType: "Lượng từ" },
      { chinese: "想", pinyin: "xiǎng", vietnamese: "muốn, nhớ, nghĩ", wordType: "Động từ" },
      { chinese: "食堂", pinyin: "shítáng", vietnamese: "nhà ăn", wordType: "Danh từ" },
      { chinese: "包子", pinyin: "bāozi", vietnamese: "bánh bao", wordType: "Danh từ" },
      { chinese: "饺子", pinyin: "jiǎozi", vietnamese: "sủi cảo", wordType: "Danh từ" },
      { chinese: "面包", pinyin: "miànbāo", vietnamese: "bánh mì", wordType: "Danh từ" },
      { chinese: "面条", pinyin: "miàntiáo", vietnamese: "mì", wordType: "Danh từ" },
      { chinese: "鸡蛋", pinyin: "jīdàn", vietnamese: "trứng gà", wordType: "Danh từ" },
      { chinese: "肉", pinyin: "ròu", vietnamese: "thịt", wordType: "Danh từ" },
      { chinese: "鸡肉", pinyin: "jīròu", vietnamese: "thịt gà", wordType: "Danh từ" },
      { chinese: "猪肉", pinyin: "zhūròu", vietnamese: "thịt lợn", wordType: "Danh từ" },
      { chinese: "牛肉", pinyin: "niúròu", vietnamese: "thịt bò", wordType: "Danh từ" },
      { chinese: "鱼", pinyin: "yú", vietnamese: "cá", wordType: "Danh từ" },
      { chinese: "汤", pinyin: "tāng", vietnamese: "canh", wordType: "Danh từ" },
      { chinese: "菜", pinyin: "cài", vietnamese: "món ăn", wordType: "Danh từ" },
      { chinese: "蔬菜", pinyin: "shūcài", vietnamese: "rau", wordType: "Danh từ" },
      { chinese: "些", pinyin: "xiē", vietnamese: "vài, những", wordType: "Lượng từ" },
      { chinese: "过", pinyin: "guò", vietnamese: "từng (trợ từ động thái)", wordType: "Trợ từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Hôm nay cô ấy đi làm rất sớm.", chineseSentence: "今天她上班很早。", pinyin: "jīntiān tā shàngbān hěn zǎo." },
      { vietnameseSentence: "Trưa nay tôi ăn một bát cơm.", chineseSentence: "今天中午我吃了一碗饭。", pinyin: "jīntiān zhōngwǔ wǒ chī le yì wǎn fàn." },
      { vietnameseSentence: "Bạn thường ăn sáng không?", chineseSentence: "你常吃早饭吗？", pinyin: "nǐ cháng chī zǎofàn ma?" },
      { vietnameseSentence: "Bạn đói không?", chineseSentence: "你饿不饿？", pinyin: "nǐ è bu è?" },
      { vietnameseSentence: "Bạn ăn no chưa?", chineseSentence: "你吃饱了吗？", pinyin: "nǐ chī bǎo le ma?" },
      { vietnameseSentence: "Tôi muốn uống cà phê.", chineseSentence: "我想喝咖啡。", pinyin: "wǒ xiǎng hē kāfēi." },
      { vietnameseSentence: "Ăn nhiều rau, ăn ít thịt.", chineseSentence: "多吃蔬菜，少吃肉。", pinyin: "duō chī shūcài, shǎo chī ròu." },
      { vietnameseSentence: "Uống nhiều nước rất tốt cho sức khỏe.", chineseSentence: "多喝水对身体很好。", pinyin: "duō hē shuǐ duì shēntǐ hěn hǎo." },
      { vietnameseSentence: "Bạn từng đi Trung Quốc chưa?", chineseSentence: "你去过中国吗？", pinyin: "nǐ qù guò zhōngguó ma?" },
      { vietnameseSentence: "Tôi chưa từng đi Trung Quốc.", chineseSentence: "我还没去过中国。", pinyin: "wǒ hái méi qù guò zhōngguó." },
      { vietnameseSentence: "Tôi thích ăn nhất là thịt gà và thịt bò.", chineseSentence: "我最喜欢吃鸡肉和牛肉。", pinyin: "wǒ zuì xǐhuan chī jīròu hé niúròu." },
      { vietnameseSentence: "Trưa nay bạn ăn cơm ở đâu?", chineseSentence: "今天中午你在哪儿吃饭？", pinyin: "jīntiān zhōngwǔ nǐ zài nǎr chī fàn?" },
    ],
    sentence: [
      { correctSentence: "你常吃早饭吗", pinyin: "nǐ cháng chī zǎofàn ma", vietnameseMeaning: "Bạn thường ăn sáng không?" },
      { correctSentence: "你饿不饿", pinyin: "nǐ è bu è", vietnameseMeaning: "Bạn đói không?" },
      { correctSentence: "我想喝咖啡", pinyin: "wǒ xiǎng hē kāfēi", vietnameseMeaning: "Tôi muốn uống cà phê." },
      { correctSentence: "我还没去过中国", pinyin: "wǒ hái méi qù guò zhōngguó", vietnameseMeaning: "Tôi chưa từng đi Trung Quốc." },
      { correctSentence: "你公司有没有食堂", pinyin: "nǐ gōngsī yǒu méiyǒu shítáng", vietnameseMeaning: "Công ty bạn có nhà ăn không?" },
      { correctSentence: "多吃蔬菜少吃肉", pinyin: "duō chī shūcài shǎo chī ròu", vietnameseMeaning: "Ăn nhiều rau, ăn ít thịt." },
    ],
  },
];
