// ───────────────────────────────────────────────────────────
// Nội dung "ĐỀ CƯƠNG ÔN TẬP SC1 – BÀI TẬP" — 8 chủ đề
// Đáp án tiếng Trung + pinyin chuẩn HSK1, soạn từ file PDF.
//
// Mỗi chủ đề (CHỦ ĐỀ) = 1 "Bài" (level) riêng.
// 3 loại bài tập tái dùng engine sẵn có:
//   translation         : Gõ từ vựng / Dịch nghĩa (Việt <-> Trung)
//   sentenceTranslation : Dịch câu (Việt -> Trung)
//   sentence            : Sắp xếp câu (ghép ký tự thành câu đúng)
//
// Lưu ý: các dạng điền chỗ trống / nối / viết đoạn văn tự luận
// KHÔNG đưa vào vì không có đáp án đơn nhất để chấm tự động.
// ───────────────────────────────────────────────────────────

export const CHAPTERS = [
  // ═══════════════ CHỦ ĐỀ 1 : 你好！═══════════════
  {
    name: "Bài 1 · 你好！",
    translation: [
      { chinese: "你好", pinyin: "nǐ hǎo", vietnamese: "xin chào", wordType: "Cụm từ" },
      { chinese: "老师", pinyin: "lǎoshī", vietnamese: "thầy/cô giáo", wordType: "Danh từ" },
      { chinese: "学生", pinyin: "xuésheng", vietnamese: "học sinh", wordType: "Danh từ" },
      { chinese: "最近", pinyin: "zuìjìn", vietnamese: "gần đây", wordType: "Danh từ" },
      { chinese: "忙", pinyin: "máng", vietnamese: "bận", wordType: "Tính từ" },
      { chinese: "工作", pinyin: "gōngzuò", vietnamese: "công việc, làm việc", wordType: "Danh/Động từ" },
      { chinese: "身体", pinyin: "shēntǐ", vietnamese: "sức khỏe, cơ thể", wordType: "Danh từ" },
      { chinese: "呢", pinyin: "ne", vietnamese: "(trợ từ nghi vấn)", wordType: "Trợ từ" },
      { chinese: "也是", pinyin: "yěshì", vietnamese: "cũng là", wordType: "Cụm từ" },
      { chinese: "不", pinyin: "bù", vietnamese: "không", wordType: "Phó từ" },
      { chinese: "大", pinyin: "dà", vietnamese: "to, lớn", wordType: "Tính từ" },
      { chinese: "好吃", pinyin: "hǎochī", vietnamese: "ngon (đồ ăn)", wordType: "Tính từ" },
      { chinese: "水果", pinyin: "shuǐguǒ", vietnamese: "hoa quả", wordType: "Danh từ" },
      { chinese: "喜欢", pinyin: "xǐhuan", vietnamese: "thích", wordType: "Động từ" },
      { chinese: "好久不见", pinyin: "hǎojiǔ bújiàn", vietnamese: "lâu rồi không gặp", wordType: "Cụm từ" },
      { chinese: "的", pinyin: "de", vietnamese: "(trợ từ kết cấu)", wordType: "Trợ từ" },
      { chinese: "钱", pinyin: "qián", vietnamese: "tiền", wordType: "Danh từ" },
      { chinese: "谢谢", pinyin: "xièxie", vietnamese: "cảm ơn", wordType: "Động từ" },
      { chinese: "不客气", pinyin: "bú kèqi", vietnamese: "đừng khách sáo", wordType: "Cụm từ" },
      { chinese: "王", pinyin: "wáng", vietnamese: "Vương (họ)", wordType: "Danh từ" },
      { chinese: "咖啡", pinyin: "kāfēi", vietnamese: "cà phê", wordType: "Danh từ" },
      { chinese: "吗", pinyin: "ma", vietnamese: "(trợ từ nghi vấn)", wordType: "Trợ từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Gần đây bạn khỏe không?", chineseSentence: "最近你好吗？", pinyin: "zuìjìn nǐ hǎo ma?" },
      { vietnameseSentence: "Bạn ăn hoa quả không?", chineseSentence: "你吃水果吗？", pinyin: "nǐ chī shuǐguǒ ma?" },
      { vietnameseSentence: "Cô ấy uống cà phê không?", chineseSentence: "她喝咖啡吗？", pinyin: "tā hē kāfēi ma?" },
      { vietnameseSentence: "Anh ấy là thầy giáo à?", chineseSentence: "他是老师吗？", pinyin: "tā shì lǎoshī ma?" },
      { vietnameseSentence: "Ông ấy là giám đốc Vương, phải không?", chineseSentence: "他是王经理，对吗？", pinyin: "tā shì wáng jīnglǐ, duì ma?" },
      { vietnameseSentence: "Bạn thích tiền không?", chineseSentence: "你喜欢钱吗？", pinyin: "nǐ xǐhuan qián ma?" },
      { vietnameseSentence: "Hoa quả ngon không?", chineseSentence: "水果好吃吗？", pinyin: "shuǐguǒ hǎochī ma?" },
      { vietnameseSentence: "Cà phê ngon không?", chineseSentence: "咖啡好喝吗？", pinyin: "kāfēi hǎohē ma?" },
      { vietnameseSentence: "Cô ấy xinh không?", chineseSentence: "她漂亮吗？", pinyin: "tā piàoliang ma?" },
      { vietnameseSentence: "Anh ấy đẹp trai không?", chineseSentence: "他帅吗？", pinyin: "tā shuài ma?" },
      { vietnameseSentence: "Gần đây bạn bận không?", chineseSentence: "最近你忙吗？", pinyin: "zuìjìn nǐ máng ma?" },
      { vietnameseSentence: "Sức khỏe của bạn tốt không?", chineseSentence: "你的身体好吗？", pinyin: "nǐ de shēntǐ hǎo ma?" },
      { vietnameseSentence: "Cô ấy rất tốt.", chineseSentence: "她很好。", pinyin: "tā hěn hǎo." },
      { vietnameseSentence: "Anh ấy rất đẹp trai.", chineseSentence: "他很帅。", pinyin: "tā hěn shuài." },
      { vietnameseSentence: "Hoa quả rất ngon.", chineseSentence: "水果很好吃。", pinyin: "shuǐguǒ hěn hǎochī." },
      { vietnameseSentence: "Tôi rất thích cô ấy.", chineseSentence: "我很喜欢她。", pinyin: "wǒ hěn xǐhuan tā." },
      { vietnameseSentence: "Cô ấy bận lắm.", chineseSentence: "她太忙了。", pinyin: "tā tài máng le." },
      { vietnameseSentence: "Anh ấy không tốt lắm.", chineseSentence: "他不太好。", pinyin: "tā bú tài hǎo." },
      { vietnameseSentence: "Bạn là thầy giáo à?", chineseSentence: "你是老师吗？", pinyin: "nǐ shì lǎoshī ma?" },
      { vietnameseSentence: "Cô ấy không phải người tốt.", chineseSentence: "她不是好人。", pinyin: "tā bú shì hǎo rén." },
    ],
    sentence: [
      { correctSentence: "最近你好吗", pinyin: "zuìjìn nǐ hǎo ma", vietnameseMeaning: "Gần đây bạn khỏe không?" },
      { correctSentence: "我最近很好", pinyin: "wǒ zuìjìn hěn hǎo", vietnameseMeaning: "Gần đây tôi rất khỏe." },
      { correctSentence: "阮老师忙吗", pinyin: "ruǎn lǎoshī máng ma", vietnameseMeaning: "Cô Nguyễn có bận không?" },
      { correctSentence: "他最近工作很忙", pinyin: "tā zuìjìn gōngzuò hěn máng", vietnameseMeaning: "Gần đây công việc của anh ấy rất bận." },
      { correctSentence: "你吃水果吗", pinyin: "nǐ chī shuǐguǒ ma", vietnameseMeaning: "Bạn ăn hoa quả không?" },
      { correctSentence: "他不吃水果", pinyin: "tā bù chī shuǐguǒ", vietnameseMeaning: "Anh ấy không ăn hoa quả." },
      { correctSentence: "我身体不太好", pinyin: "wǒ shēntǐ bú tài hǎo", vietnameseMeaning: "Sức khỏe tôi không tốt lắm." },
      { correctSentence: "你喜欢钱吗", pinyin: "nǐ xǐhuan qián ma", vietnameseMeaning: "Bạn thích tiền không?" },
      { correctSentence: "我很喜欢钱", pinyin: "wǒ hěn xǐhuan qián", vietnameseMeaning: "Tôi rất thích tiền." },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 2 : 你是哪国人？═══════════════
  {
    name: "Bài 2 · 你是哪国人？",
    translation: [
      { chinese: "哪国人", pinyin: "nǎ guórén", vietnamese: "người nước nào", wordType: "Cụm từ" },
      { chinese: "名字", pinyin: "míngzi", vietnamese: "tên", wordType: "Danh từ" },
      { chinese: "什么", pinyin: "shénme", vietnamese: "gì, cái gì", wordType: "Đại từ" },
      { chinese: "叫", pinyin: "jiào", vietnamese: "gọi, tên là", wordType: "Động từ" },
      { chinese: "还", pinyin: "hái", vietnamese: "còn, vẫn", wordType: "Phó từ" },
      { chinese: "认识", pinyin: "rènshi", vietnamese: "quen biết, nhận biết", wordType: "Động từ" },
      { chinese: "高兴", pinyin: "gāoxìng", vietnamese: "vui mừng", wordType: "Tính từ" },
      { chinese: "问", pinyin: "wèn", vietnamese: "hỏi", wordType: "Động từ" },
      { chinese: "请", pinyin: "qǐng", vietnamese: "mời, xin", wordType: "Động từ" },
      { chinese: "越南", pinyin: "yuènán", vietnamese: "Việt Nam", wordType: "Danh từ" },
      { chinese: "中国", pinyin: "zhōngguó", vietnamese: "Trung Quốc", wordType: "Danh từ" },
      { chinese: "介绍", pinyin: "jièshào", vietnamese: "giới thiệu", wordType: "Động từ" },
      { chinese: "哪", pinyin: "nǎ", vietnamese: "nào", wordType: "Đại từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Người nào là người Trung Quốc?", chineseSentence: "哪个人是中国人？", pinyin: "nǎ ge rén shì zhōngguó rén?" },
      { vietnameseSentence: "Cái điện thoại nào là của bạn?", chineseSentence: "哪个手机是你的？", pinyin: "nǎ ge shǒujī shì nǐ de?" },
      { vietnameseSentence: "Bạn thích nước nào?", chineseSentence: "你喜欢哪个国家？", pinyin: "nǐ xǐhuan nǎ ge guójiā?" },
      { vietnameseSentence: "Bạn làm việc ở công ty nào?", chineseSentence: "你在哪个公司工作？", pinyin: "nǐ zài nǎ ge gōngsī gōngzuò?" },
      { vietnameseSentence: "Bạn uống trà hay là uống cà phê?", chineseSentence: "你喝茶还是喝咖啡？", pinyin: "nǐ hē chá háishi hē kāfēi?" },
      { vietnameseSentence: "Bạn là người nước Anh hay người nước Mỹ?", chineseSentence: "你是英国人还是美国人？", pinyin: "nǐ shì yīngguó rén háishi měiguó rén?" },
      { vietnameseSentence: "Bạn ăn cơm hay ăn hoa quả?", chineseSentence: "你吃饭还是吃水果？", pinyin: "nǐ chī fàn háishi chī shuǐguǒ?" },
      { vietnameseSentence: "Bạn học tiếng Trung hay tiếng Anh?", chineseSentence: "你学中文还是英文？", pinyin: "nǐ xué zhōngwén háishi yīngwén?" },
      { vietnameseSentence: "Chúng tôi vẫn là bạn tốt.", chineseSentence: "我们还是好朋友。", pinyin: "wǒmen háishi hǎo péngyou." },
      { vietnameseSentence: "Bạn là người Trung Quốc à?", chineseSentence: "你是不是中国人？", pinyin: "nǐ shì bu shì zhōngguó rén?" },
      { vietnameseSentence: "Bạn ăn hoa quả không?", chineseSentence: "你吃不吃水果？", pinyin: "nǐ chī bu chī shuǐguǒ?" },
      { vietnameseSentence: "Bạn học tiếng Trung không?", chineseSentence: "你学不学中文？", pinyin: "nǐ xué bu xué zhōngwén?" },
      { vietnameseSentence: "Cô ấy xinh không?", chineseSentence: "她漂不漂亮？", pinyin: "tā piào bu piàoliang?" },
      { vietnameseSentence: "Cơm ngon không?", chineseSentence: "饭好不好吃？", pinyin: "fàn hǎo bu hǎochī?" },
      { vietnameseSentence: "Hôm nay cậu vui không?", chineseSentence: "今天你高不高兴？", pinyin: "jīntiān nǐ gāo bu gāoxìng?" },
      { vietnameseSentence: "Tiếng Trung khó không?", chineseSentence: "中文难不难？", pinyin: "zhōngwén nán bu nán?" },
      { vietnameseSentence: "Bạn thích cô ấy không?", chineseSentence: "你喜不喜欢她？", pinyin: "nǐ xǐ bu xǐhuan tā?" },
    ],
    sentence: [
      { correctSentence: "你叫什么名字", pinyin: "nǐ jiào shénme míngzi", vietnameseMeaning: "Bạn tên là gì?" },
      { correctSentence: "你是哪国人", pinyin: "nǐ shì nǎ guórén", vietnameseMeaning: "Bạn là người nước nào?" },
      { correctSentence: "你喝茶吗", pinyin: "nǐ hē chá ma", vietnameseMeaning: "Bạn uống trà không?" },
      { correctSentence: "咖啡好喝吗", pinyin: "kāfēi hǎohē ma", vietnameseMeaning: "Cà phê ngon không?" },
      { correctSentence: "我问你什么", pinyin: "wǒ wèn nǐ shénme", vietnameseMeaning: "Tôi hỏi bạn cái gì?" },
      { correctSentence: "你认识他吗", pinyin: "nǐ rènshi tā ma", vietnameseMeaning: "Bạn quen anh ấy không?" },
      { correctSentence: "我来介绍一下儿", pinyin: "wǒ lái jièshào yíxiàr", vietnameseMeaning: "Tôi giới thiệu một chút." },
      { correctSentence: "他来越南玩儿", pinyin: "tā lái yuènán wánr", vietnameseMeaning: "Anh ấy đến Việt Nam chơi." },
      { correctSentence: "你最近忙不忙", pinyin: "nǐ zuìjìn máng bu máng", vietnameseMeaning: "Gần đây bạn có bận không?" },
      { correctSentence: "你是不是中国人", pinyin: "nǐ shì bu shì zhōngguó rén", vietnameseMeaning: "Bạn có phải người Trung Quốc không?" },
      { correctSentence: "你学不学中文", pinyin: "nǐ xué bu xué zhōngwén", vietnameseMeaning: "Bạn có học tiếng Trung không?" },
      { correctSentence: "你高兴吗", pinyin: "nǐ gāoxìng ma", vietnameseMeaning: "Bạn vui không?" },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 3 : 汉语不太难。═══════════════
  {
    name: "Bài 3 · 汉语不太难",
    translation: [
      { chinese: "汉语", pinyin: "hànyǔ", vietnamese: "tiếng Hán", wordType: "Danh từ" },
      { chinese: "中文", pinyin: "zhōngwén", vietnamese: "tiếng Trung", wordType: "Danh từ" },
      { chinese: "越南语", pinyin: "yuènányǔ", vietnamese: "tiếng Việt", wordType: "Danh từ" },
      { chinese: "学", pinyin: "xué", vietnamese: "học", wordType: "Động từ" },
      { chinese: "难", pinyin: "nán", vietnamese: "khó", wordType: "Tính từ" },
      { chinese: "容易", pinyin: "róngyì", vietnamese: "dễ dàng", wordType: "Tính từ" },
      { chinese: "觉得", pinyin: "juéde", vietnamese: "cảm thấy", wordType: "Động từ" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", vietnamese: "như thế nào", wordType: "Đại từ" },
      { chinese: "会", pinyin: "huì", vietnamese: "biết, có thể", wordType: "Động từ" },
      { chinese: "知道", pinyin: "zhīdào", vietnamese: "biết", wordType: "Động từ" },
      { chinese: "说", pinyin: "shuō", vietnamese: "nói", wordType: "Động từ" },
      { chinese: "听", pinyin: "tīng", vietnamese: "nghe", wordType: "Động từ" },
      { chinese: "看", pinyin: "kàn", vietnamese: "xem, nhìn", wordType: "Động từ" },
      { chinese: "和", pinyin: "hé", vietnamese: "và", wordType: "Liên từ" },
      { chinese: "但是", pinyin: "dànshì", vietnamese: "nhưng", wordType: "Liên từ" },
      { chinese: "比较", pinyin: "bǐjiào", vietnamese: "tương đối, so sánh", wordType: "Phó từ" },
      { chinese: "汉字", pinyin: "hànzì", vietnamese: "chữ Hán", wordType: "Danh từ" },
      { chinese: "写", pinyin: "xiě", vietnamese: "viết", wordType: "Động từ" },
      { chinese: "打", pinyin: "dǎ", vietnamese: "gõ, đánh", wordType: "Động từ" },
      { chinese: "同学", pinyin: "tóngxué", vietnamese: "bạn học", wordType: "Danh từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Cô giáo của tôi.", chineseSentence: "我的老师。", pinyin: "wǒ de lǎoshī." },
      { vietnameseSentence: "Tiền của anh ấy.", chineseSentence: "他的钱。", pinyin: "tā de qián." },
      { vietnameseSentence: "Xe của ai?", chineseSentence: "谁的车？", pinyin: "shéi de chē?" },
      { vietnameseSentence: "Sách của cô ấy.", chineseSentence: "她的书。", pinyin: "tā de shū." },
      { vietnameseSentence: "Gần đây bạn học tập như thế nào?", chineseSentence: "最近你学习怎么样？", pinyin: "zuìjìn nǐ xuéxí zěnmeyàng?" },
      { vietnameseSentence: "Công việc của bạn như thế nào rồi?", chineseSentence: "你的工作怎么样？", pinyin: "nǐ de gōngzuò zěnmeyàng?" },
      { vietnameseSentence: "Cô ấy viết chữ Hán như thế nào?", chineseSentence: "她写汉字怎么样？", pinyin: "tā xiě hànzì zěnmeyàng?" },
      { vietnameseSentence: "Cô ấy đi ăn cơm.", chineseSentence: "她去吃饭。", pinyin: "tā qù chī fàn." },
      { vietnameseSentence: "Cô ấy đi chơi rồi.", chineseSentence: "她去玩儿了。", pinyin: "tā qù wánr le." },
      { vietnameseSentence: "Cô ấy đi Trung Quốc du học.", chineseSentence: "她去中国留学。", pinyin: "tā qù zhōngguó liúxué." },
      { vietnameseSentence: "Gần đây bạn có thời gian không?", chineseSentence: "最近你有时间吗？", pinyin: "zuìjìn nǐ yǒu shíjiān ma?" },
      { vietnameseSentence: "Bạn có tiền không?", chineseSentence: "你有钱吗？", pinyin: "nǐ yǒu qián ma?" },
      { vietnameseSentence: "Tôi có một cái điện thoại màu trắng.", chineseSentence: "我有一个白色的手机。", pinyin: "wǒ yǒu yí ge báisè de shǒujī." },
      { vietnameseSentence: "Tôi hết tiền rồi.", chineseSentence: "我没有钱了。", pinyin: "wǒ méiyǒu qián le." },
      { vietnameseSentence: "Hết cơm rồi.", chineseSentence: "没有饭了。", pinyin: "méiyǒu fàn le." },
    ],
    sentence: [
      { correctSentence: "你学什么", pinyin: "nǐ xué shénme", vietnameseMeaning: "Bạn học gì?" },
      { correctSentence: "他中文说得怎么样", pinyin: "tā zhōngwén shuō de zěnmeyàng", vietnameseMeaning: "Anh ấy nói tiếng Trung như thế nào?" },
      { correctSentence: "你会写汉字吗", pinyin: "nǐ huì xiě hànzì ma", vietnameseMeaning: "Bạn biết viết chữ Hán không?" },
      { correctSentence: "打汉字比较简单", pinyin: "dǎ hànzì bǐjiào jiǎndān", vietnameseMeaning: "Gõ chữ Hán tương đối đơn giản." },
      { correctSentence: "我的老师很好", pinyin: "wǒ de lǎoshī hěn hǎo", vietnameseMeaning: "Cô giáo tôi rất tốt." },
      { correctSentence: "他去中国学中文", pinyin: "tā qù zhōngguó xué zhōngwén", vietnameseMeaning: "Anh ấy đi Trung Quốc học tiếng Trung." },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 4 : 你家有几口？═══════════════
  {
    name: "Bài 4 · 你家有几口？",
    translation: [
      { chinese: "家庭", pinyin: "jiātíng", vietnamese: "gia đình", wordType: "Danh từ" },
      { chinese: "老家", pinyin: "lǎojiā", vietnamese: "quê nhà", wordType: "Danh từ" },
      { chinese: "爸妈", pinyin: "bàmā", vietnamese: "bố mẹ", wordType: "Danh từ" },
      { chinese: "老公", pinyin: "lǎogōng", vietnamese: "chồng", wordType: "Danh từ" },
      { chinese: "老婆", pinyin: "lǎopó", vietnamese: "vợ", wordType: "Danh từ" },
      { chinese: "兄弟姐妹", pinyin: "xiōngdì jiěmèi", vietnamese: "anh chị em", wordType: "Danh từ" },
      { chinese: "孩子", pinyin: "háizi", vietnamese: "con cái", wordType: "Danh từ" },
      { chinese: "朋友", pinyin: "péngyou", vietnamese: "bạn bè", wordType: "Danh từ" },
      { chinese: "漂亮", pinyin: "piàoliang", vietnamese: "xinh đẹp", wordType: "Tính từ" },
      { chinese: "帅", pinyin: "shuài", vietnamese: "đẹp trai", wordType: "Tính từ" },
      { chinese: "谁", pinyin: "shéi", vietnamese: "ai", wordType: "Đại từ" },
      { chinese: "女儿", pinyin: "nǚ'ér", vietnamese: "con gái", wordType: "Danh từ" },
      { chinese: "儿子", pinyin: "érzi", vietnamese: "con trai", wordType: "Danh từ" },
      { chinese: "几", pinyin: "jǐ", vietnamese: "mấy", wordType: "Đại từ" },
      { chinese: "已经", pinyin: "yǐjīng", vietnamese: "đã, rồi", wordType: "Phó từ" },
      { chinese: "都", pinyin: "dōu", vietnamese: "đều", wordType: "Phó từ" },
      { chinese: "去", pinyin: "qù", vietnamese: "đi", wordType: "Động từ" },
      { chinese: "回", pinyin: "huí", vietnamese: "về", wordType: "Động từ" },
      { chinese: "在", pinyin: "zài", vietnamese: "ở, đang", wordType: "Động/Giới từ" },
      { chinese: "公司", pinyin: "gōngsī", vietnamese: "công ty", wordType: "Danh từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Nhà bạn ở đâu?", chineseSentence: "你家在哪儿？", pinyin: "nǐ jiā zài nǎr?" },
      { vietnameseSentence: "Công ty của bạn ở đâu?", chineseSentence: "你的公司在哪儿？", pinyin: "nǐ de gōngsī zài nǎr?" },
      { vietnameseSentence: "Bạn đang ở đâu vậy?", chineseSentence: "你在哪儿？", pinyin: "nǐ zài nǎr?" },
      { vietnameseSentence: "Quê tôi ở Bắc Ninh.", chineseSentence: "我的老家在北宁。", pinyin: "wǒ de lǎojiā zài běiníng." },
      { vietnameseSentence: "Bạn ăn cơm ở đâu?", chineseSentence: "你在哪儿吃饭？", pinyin: "nǐ zài nǎr chī fàn?" },
      { vietnameseSentence: "Hiện tại bạn làm việc ở đâu?", chineseSentence: "你现在在哪儿工作？", pinyin: "nǐ xiànzài zài nǎr gōngzuò?" },
      { vietnameseSentence: "Anh ấy về nhà ăn cơm.", chineseSentence: "他回家吃饭。", pinyin: "tā huí jiā chī fàn." },
      { vietnameseSentence: "Nhà bạn có mấy người?", chineseSentence: "你家有几口人？", pinyin: "nǐ jiā yǒu jǐ kǒu rén?" },
      { vietnameseSentence: "Bạn có mấy chị gái?", chineseSentence: "你有几个姐姐？", pinyin: "nǐ yǒu jǐ ge jiějie?" },
      { vietnameseSentence: "Bạn có mấy đứa con?", chineseSentence: "你有几个孩子？", pinyin: "nǐ yǒu jǐ ge háizi?" },
      { vietnameseSentence: "Bạn trai cô ấy là ai?", chineseSentence: "她的男朋友是谁？", pinyin: "tā de nán péngyou shì shéi?" },
      { vietnameseSentence: "Bố của bạn là ai?", chineseSentence: "你的爸爸是谁？", pinyin: "nǐ de bàba shì shéi?" },
      { vietnameseSentence: "Ai là cô giáo của bạn?", chineseSentence: "谁是你的老师？", pinyin: "shéi shì nǐ de lǎoshī?" },
      { vietnameseSentence: "Nó là tiền của ai?", chineseSentence: "这是谁的钱？", pinyin: "zhè shì shéi de qián?" },
      { vietnameseSentence: "Ai thích học tiếng Trung?", chineseSentence: "谁喜欢学中文？", pinyin: "shéi xǐhuan xué zhōngwén?" },
    ],
    sentence: [
      { correctSentence: "你家有几个人", pinyin: "nǐ jiā yǒu jǐ ge rén", vietnameseMeaning: "Nhà bạn có mấy người?" },
      { correctSentence: "你的老家在哪儿", pinyin: "nǐ de lǎojiā zài nǎr", vietnameseMeaning: "Quê bạn ở đâu?" },
      { correctSentence: "你在哪儿工作", pinyin: "nǐ zài nǎr gōngzuò", vietnameseMeaning: "Bạn làm việc ở đâu?" },
      { correctSentence: "我已经结婚了", pinyin: "wǒ yǐjīng jiéhūn le", vietnameseMeaning: "Tôi đã kết hôn rồi." },
      { correctSentence: "他有两个孩子", pinyin: "tā yǒu liǎng ge háizi", vietnameseMeaning: "Anh ấy có hai đứa con." },
      { correctSentence: "谁是你的老师", pinyin: "shéi shì nǐ de lǎoshī", vietnameseMeaning: "Ai là cô giáo của bạn?" },
      { correctSentence: "谁给你钱", pinyin: "shéi gěi nǐ qián", vietnameseMeaning: "Ai cho bạn tiền?" },
      { correctSentence: "我和他都是越南人", pinyin: "wǒ hé tā dōu shì yuènán rén", vietnameseMeaning: "Tôi và anh ấy đều là người Việt Nam." },
      { correctSentence: "你在哪儿学中文", pinyin: "nǐ zài nǎr xué zhōngwén", vietnameseMeaning: "Bạn học tiếng Trung ở đâu?" },
      { correctSentence: "他的老婆很漂亮", pinyin: "tā de lǎopó hěn piàoliang", vietnameseMeaning: "Vợ anh ấy rất xinh." },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 5 : 明天见！═══════════════
  {
    name: "Bài 5 · 明天见！",
    translation: [
      { chinese: "哪天", pinyin: "nǎ tiān", vietnamese: "ngày nào", wordType: "Cụm từ" },
      { chinese: "昨天", pinyin: "zuótiān", vietnamese: "hôm qua", wordType: "Danh từ" },
      { chinese: "今天", pinyin: "jīntiān", vietnamese: "hôm nay", wordType: "Danh từ" },
      { chinese: "明天", pinyin: "míngtiān", vietnamese: "ngày mai", wordType: "Danh từ" },
      { chinese: "天天", pinyin: "tiāntiān", vietnamese: "ngày nào cũng", wordType: "Phó từ" },
      { chinese: "星期几", pinyin: "xīngqī jǐ", vietnamese: "thứ mấy", wordType: "Cụm từ" },
      { chinese: "周末", pinyin: "zhōumò", vietnamese: "cuối tuần", wordType: "Danh từ" },
      { chinese: "年", pinyin: "nián", vietnamese: "năm", wordType: "Danh từ" },
      { chinese: "月", pinyin: "yuè", vietnamese: "tháng", wordType: "Danh từ" },
      { chinese: "日/号", pinyin: "rì / hào", vietnamese: "ngày", wordType: "Danh từ" },
      { chinese: "一起", pinyin: "yìqǐ", vietnamese: "cùng nhau", wordType: "Phó từ" },
      { chinese: "跟", pinyin: "gēn", vietnamese: "với, cùng", wordType: "Giới từ" },
      { chinese: "常常", pinyin: "chángcháng", vietnamese: "thường xuyên", wordType: "Phó từ" },
      { chinese: "生日", pinyin: "shēngrì", vietnamese: "sinh nhật", wordType: "Danh từ" },
      { chinese: "关系", pinyin: "guānxì", vietnamese: "quan hệ", wordType: "Danh từ" },
      { chinese: "同事", pinyin: "tóngshì", vietnamese: "đồng nghiệp", wordType: "Danh từ" },
      { chinese: "上班", pinyin: "shàngbān", vietnamese: "đi làm", wordType: "Động từ" },
      { chinese: "下班", pinyin: "xiàbān", vietnamese: "tan làm", wordType: "Động từ" },
      { chinese: "加班", pinyin: "jiābān", vietnamese: "tăng ca", wordType: "Động từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Hôm nay là thứ mấy?", chineseSentence: "今天星期几？", pinyin: "jīntiān xīngqī jǐ?" },
      { vietnameseSentence: "Thứ mấy bạn phải đi học tiếng Trung?", chineseSentence: "你星期几要去学中文？", pinyin: "nǐ xīngqī jǐ yào qù xué zhōngwén?" },
      { vietnameseSentence: "Thứ mấy anh ấy về nước?", chineseSentence: "他星期几回国？", pinyin: "tā xīngqī jǐ huí guó?" },
      { vietnameseSentence: "Cuối tuần này tôi cùng gia đình đi du lịch.", chineseSentence: "这个周末我跟家人一起去旅游。", pinyin: "zhège zhōumò wǒ gēn jiārén yìqǐ qù lǚyóu." },
      { vietnameseSentence: "Hôm qua tôi cùng vài người bạn đi nhà hàng ăn cơm.", chineseSentence: "昨天我跟几个朋友去饭店吃饭。", pinyin: "zuótiān wǒ gēn jǐ ge péngyou qù fàndiàn chī fàn." },
      { vietnameseSentence: "Xin lỗi, tôi nhìn nhầm rồi.", chineseSentence: "对不起，我看错了。", pinyin: "duìbuqǐ, wǒ kàn cuò le." },
      { vietnameseSentence: "Bạn viết nhầm tên tôi rồi.", chineseSentence: "你写错我的名字了。", pinyin: "nǐ xiě cuò wǒ de míngzi le." },
      { vietnameseSentence: "Hôm qua các bạn gặp nhau ở đâu?", chineseSentence: "你们昨天在哪儿见面？", pinyin: "nǐmen zuótiān zài nǎr jiànmiàn?" },
      { vietnameseSentence: "Ngày nào tôi cũng phải tăng ca, không có thời gian đi chơi.", chineseSentence: "天天我都要加班，没有时间去玩儿。", pinyin: "tiāntiān wǒ dōu yào jiābān, méiyǒu shíjiān qù wánr." },
      { vietnameseSentence: "Bạn và anh ấy có quan hệ gì?", chineseSentence: "你和他有什么关系？", pinyin: "nǐ hé tā yǒu shénme guānxì?" },
    ],
    sentence: [
      { correctSentence: "今天我跟他一起上课", pinyin: "jīntiān wǒ gēn tā yìqǐ shàng kè", vietnameseMeaning: "Hôm nay tôi cùng anh ấy đi học." },
      { correctSentence: "明天你有课吗", pinyin: "míngtiān nǐ yǒu kè ma", vietnameseMeaning: "Ngày mai bạn có tiết học không?" },
      { correctSentence: "我们的关系很好", pinyin: "wǒmen de guānxì hěn hǎo", vietnameseMeaning: "Quan hệ của chúng tôi rất tốt." },
      { correctSentence: "明天我们在公司见吧", pinyin: "míngtiān wǒmen zài gōngsī jiàn ba", vietnameseMeaning: "Ngày mai chúng ta gặp ở công ty nhé." },
      { correctSentence: "你周末喜欢吗", pinyin: "nǐ zhōumò xǐhuan ma", vietnameseMeaning: "Bạn thích cuối tuần không?" },
      { correctSentence: "你写错了", pinyin: "nǐ xiě cuò le", vietnameseMeaning: "Bạn viết sai rồi." },
      { correctSentence: "星期天我不要上班", pinyin: "xīngqītiān wǒ bú yào shàngbān", vietnameseMeaning: "Chủ nhật tôi không phải đi làm." },
      { correctSentence: "你在这里等我吧", pinyin: "nǐ zài zhèlǐ děng wǒ ba", vietnameseMeaning: "Bạn đợi tôi ở đây nhé." },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 6 : GIỚI THIỆU BẢN THÂN ═══════════════
  {
    name: "Bài 6 · Giới thiệu bản thân",
    translation: [
      { chinese: "先", pinyin: "xiān", vietnamese: "trước tiên", wordType: "Phó từ" },
      { chinese: "介绍", pinyin: "jièshào", vietnamese: "giới thiệu", wordType: "Động từ" },
      { chinese: "名字", pinyin: "míngzi", vietnamese: "tên", wordType: "Danh từ" },
      { chinese: "岁", pinyin: "suì", vietnamese: "tuổi", wordType: "Lượng từ" },
      { chinese: "多大", pinyin: "duō dà", vietnamese: "bao nhiêu tuổi", wordType: "Cụm từ" },
      { chinese: "几岁", pinyin: "jǐ suì", vietnamese: "mấy tuổi", wordType: "Cụm từ" },
      { chinese: "今年", pinyin: "jīnnián", vietnamese: "năm nay", wordType: "Danh từ" },
      { chinese: "住", pinyin: "zhù", vietnamese: "ở, sinh sống", wordType: "Động từ" },
      { chinese: "来自", pinyin: "láizì", vietnamese: "đến từ", wordType: "Động từ" },
      { chinese: "办公员", pinyin: "bàngōngyuán", vietnamese: "nhân viên văn phòng", wordType: "Danh từ" },
      { chinese: "爱好", pinyin: "àihào", vietnamese: "sở thích", wordType: "Danh từ" },
      { chinese: "看电影", pinyin: "kàn diànyǐng", vietnamese: "xem phim", wordType: "Cụm từ" },
      { chinese: "旅行", pinyin: "lǚxíng", vietnamese: "du lịch", wordType: "Động từ" },
      { chinese: "旅游", pinyin: "lǚyóu", vietnamese: "du lịch", wordType: "Động từ" },
      { chinese: "踢足球", pinyin: "tī zúqiú", vietnamese: "đá bóng", wordType: "Cụm từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Bạn đến từ đâu?", chineseSentence: "你从哪儿来？", pinyin: "nǐ cóng nǎr lái?" },
      { vietnameseSentence: "Tôi đến từ Quế Võ, Bắc Ninh.", chineseSentence: "我来自北宁桂武。", pinyin: "wǒ láizì běiníng guìwǔ." },
      { vietnameseSentence: "Chúng tôi đều đến từ Hàn Quốc.", chineseSentence: "我们都来自韩国。", pinyin: "wǒmen dōu láizì hánguó." },
      { vietnameseSentence: "Anh ấy không phải người Việt Nam, anh ấy đến từ Mỹ.", chineseSentence: "他不是越南人，他来自美国。", pinyin: "tā bú shì yuènán rén, tā láizì měiguó." },
      { vietnameseSentence: "Từ thứ 2 đến thứ 7 tôi đều phải đi làm.", chineseSentence: "从星期一到星期六我都要上班。", pinyin: "cóng xīngqīyī dào xīngqīliù wǒ dōu yào shàngbān." },
      { vietnameseSentence: "Từ nhà tôi đến công ty không xa lắm.", chineseSentence: "从我家到公司不太远。", pinyin: "cóng wǒ jiā dào gōngsī bú tài yuǎn." },
      { vietnameseSentence: "Trước tiên tôi xin giới thiệu một chút.", chineseSentence: "我先介绍一下。", pinyin: "wǒ xiān jièshào yíxià." },
      { vietnameseSentence: "Bạn tên là gì?", chineseSentence: "你叫什么名字？", pinyin: "nǐ jiào shénme míngzi?" },
      { vietnameseSentence: "Năm nay bạn bao nhiêu tuổi?", chineseSentence: "你今年多大？", pinyin: "nǐ jīnnián duō dà?" },
      { vietnameseSentence: "Bạn hiện tại làm công việc gì?", chineseSentence: "你现在做什么工作？", pinyin: "nǐ xiànzài zuò shénme gōngzuò?" },
      { vietnameseSentence: "Tôi vẫn còn độc thân.", chineseSentence: "我还是单身。", pinyin: "wǒ háishi dānshēn." },
      { vietnameseSentence: "Sở thích của bạn là gì?", chineseSentence: "你的爱好是什么？", pinyin: "nǐ de àihào shì shénme?" },
      { vietnameseSentence: "Tôi vẫn chưa kết hôn.", chineseSentence: "我还没结婚。", pinyin: "wǒ hái méi jiéhūn." },
    ],
    sentence: [
      { correctSentence: "她不知道我的名字", pinyin: "tā bù zhīdào wǒ de míngzi", vietnameseMeaning: "Cô ấy không biết tên tôi." },
      { correctSentence: "她的孩子今年五岁", pinyin: "tā de háizi jīnnián wǔ suì", vietnameseMeaning: "Con cô ấy năm nay 5 tuổi." },
      { correctSentence: "我还没结婚", pinyin: "wǒ hái méi jiéhūn", vietnameseMeaning: "Tôi vẫn chưa kết hôn." },
      { correctSentence: "我的老家在北宁桂武", pinyin: "wǒ de lǎojiā zài běiníng guìwǔ", vietnameseMeaning: "Quê tôi ở Quế Võ, Bắc Ninh." },
      { correctSentence: "你有时间喜欢做什么", pinyin: "nǐ yǒu shíjiān xǐhuan zuò shénme", vietnameseMeaning: "Lúc rảnh bạn thích làm gì?" },
      { correctSentence: "我的爱好是旅行和购物", pinyin: "wǒ de àihào shì lǚxíng hé gòuwù", vietnameseMeaning: "Sở thích của tôi là du lịch và mua sắm." },
      { correctSentence: "我老公很喜欢看足球", pinyin: "wǒ lǎogōng hěn xǐhuan kàn zúqiú", vietnameseMeaning: "Chồng tôi rất thích xem bóng đá." },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 7 : 你吃什么？═══════════════
  {
    name: "Bài 7 · 你吃什么？",
    translation: [
      { chinese: "吃", pinyin: "chī", vietnamese: "ăn", wordType: "Động từ" },
      { chinese: "好吃", pinyin: "hǎochī", vietnamese: "ngon (đồ ăn)", wordType: "Tính từ" },
      { chinese: "喝", pinyin: "hē", vietnamese: "uống", wordType: "Động từ" },
      { chinese: "好喝", pinyin: "hǎohē", vietnamese: "ngon (đồ uống)", wordType: "Tính từ" },
      { chinese: "早上", pinyin: "zǎoshang", vietnamese: "buổi sáng", wordType: "Danh từ" },
      { chinese: "上午", pinyin: "shàngwǔ", vietnamese: "buổi sáng (trước trưa)", wordType: "Danh từ" },
      { chinese: "中午", pinyin: "zhōngwǔ", vietnamese: "buổi trưa", wordType: "Danh từ" },
      { chinese: "下午", pinyin: "xiàwǔ", vietnamese: "buổi chiều", wordType: "Danh từ" },
      { chinese: "晚上", pinyin: "wǎnshang", vietnamese: "buổi tối", wordType: "Danh từ" },
      { chinese: "早饭", pinyin: "zǎofàn", vietnamese: "bữa sáng", wordType: "Danh từ" },
      { chinese: "午饭", pinyin: "wǔfàn", vietnamese: "bữa trưa", wordType: "Danh từ" },
      { chinese: "晚饭", pinyin: "wǎnfàn", vietnamese: "bữa tối", wordType: "Danh từ" },
      { chinese: "想", pinyin: "xiǎng", vietnamese: "muốn, nghĩ", wordType: "Động từ" },
      { chinese: "食堂", pinyin: "shítáng", vietnamese: "nhà ăn", wordType: "Danh từ" },
      { chinese: "饺子", pinyin: "jiǎozi", vietnamese: "sủi cảo", wordType: "Danh từ" },
      { chinese: "面条", pinyin: "miàntiáo", vietnamese: "mì", wordType: "Danh từ" },
      { chinese: "肉", pinyin: "ròu", vietnamese: "thịt", wordType: "Danh từ" },
      { chinese: "蔬菜", pinyin: "shūcài", vietnamese: "rau", wordType: "Danh từ" },
      { chinese: "这些", pinyin: "zhèxiē", vietnamese: "những cái này", wordType: "Đại từ" },
      { chinese: "那些", pinyin: "nàxiē", vietnamese: "những cái kia", wordType: "Đại từ" },
      { chinese: "饿", pinyin: "è", vietnamese: "đói", wordType: "Tính từ" },
      { chinese: "饱", pinyin: "bǎo", vietnamese: "no", wordType: "Tính từ" },
      { chinese: "过", pinyin: "guò", vietnamese: "(trợ từ động thái: từng)", wordType: "Trợ từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Ăn nhiều thịt không tốt cho sức khỏe.", chineseSentence: "吃很多肉对身体不好。", pinyin: "chī hěn duō ròu duì shēntǐ bù hǎo." },
      { vietnameseSentence: "Ăn hoa quả tốt cho cơ thể.", chineseSentence: "吃水果对身体很好。", pinyin: "chī shuǐguǒ duì shēntǐ hěn hǎo." },
      { vietnameseSentence: "Tôi muốn ăn những cái này.", chineseSentence: "我想吃这些。", pinyin: "wǒ xiǎng chī zhèxiē." },
      { vietnameseSentence: "Những quyển sách này là của ai vậy?", chineseSentence: "这些书是谁的？", pinyin: "zhèxiē shū shì shéi de?" },
      { vietnameseSentence: "Tôi muốn mua những đồ này.", chineseSentence: "我想买这些东西。", pinyin: "wǒ xiǎng mǎi zhèxiē dōngxi." },
      { vietnameseSentence: "Bạn từng đi Trung Quốc chưa?", chineseSentence: "你去过中国吗？", pinyin: "nǐ qù guò zhōngguó ma?" },
      { vietnameseSentence: "Anh ấy từng đến nhà tôi chơi rồi.", chineseSentence: "他来过我家玩儿了。", pinyin: "tā lái guò wǒ jiā wánr le." },
      { vietnameseSentence: "Bạn từng xem bộ phim này chưa?", chineseSentence: "你看过这部电影吗？", pinyin: "nǐ kàn guò zhè bù diànyǐng ma?" },
      { vietnameseSentence: "Trưa nay bạn ăn cơm ở đâu?", chineseSentence: "今天中午你在哪儿吃饭？", pinyin: "jīntiān zhōngwǔ nǐ zài nǎr chī fàn?" },
      { vietnameseSentence: "Bữa tối bạn ăn cái gì?", chineseSentence: "晚饭你吃什么？", pinyin: "wǎnfàn nǐ chī shénme?" },
      { vietnameseSentence: "Bạn biết nấu ăn không?", chineseSentence: "你会做饭吗？", pinyin: "nǐ huì zuò fàn ma?" },
      { vietnameseSentence: "Tôi rất thích ăn thịt gà và thịt lợn.", chineseSentence: "我很喜欢吃鸡肉和猪肉。", pinyin: "wǒ hěn xǐhuan chī jīròu hé zhūròu." },
    ],
    sentence: [
      { correctSentence: "这些东西都是你买的吗", pinyin: "zhèxiē dōngxi dōu shì nǐ mǎi de ma", vietnameseMeaning: "Những đồ này đều là bạn mua à?" },
      { correctSentence: "那些人都是我的同事", pinyin: "nàxiē rén dōu shì wǒ de tóngshì", vietnameseMeaning: "Những người kia đều là đồng nghiệp của tôi." },
      { correctSentence: "昨天晚上我去看电影", pinyin: "zuótiān wǎnshang wǒ qù kàn diànyǐng", vietnameseMeaning: "Tối hôm qua tôi đi xem phim." },
      { correctSentence: "我还没吃过中国菜", pinyin: "wǒ hái méi chī guò zhōngguó cài", vietnameseMeaning: "Tôi chưa từng ăn món Trung Quốc." },
      { correctSentence: "你最喜欢吃什么", pinyin: "nǐ zuì xǐhuan chī shénme", vietnameseMeaning: "Bạn thích ăn gì nhất?" },
      { correctSentence: "你饿了吗", pinyin: "nǐ è le ma", vietnameseMeaning: "Bạn đói chưa?" },
      { correctSentence: "晚上我常回家吃饭", pinyin: "wǎnshang wǒ cháng huí jiā chī fàn", vietnameseMeaning: "Buổi tối tôi thường về nhà ăn cơm." },
      { correctSentence: "你公司有没有食堂", pinyin: "nǐ gōngsī yǒu méiyǒu shítáng", vietnameseMeaning: "Công ty bạn có nhà ăn không?" },
    ],
  },

  // ═══════════════ CHỦ ĐỀ 8 : 一斤苹果多少钱？═══════════════
  {
    name: "Bài 8 · 一斤苹果多少钱？",
    translation: [
      { chinese: "买", pinyin: "mǎi", vietnamese: "mua", wordType: "Động từ" },
      { chinese: "卖", pinyin: "mài", vietnamese: "bán", wordType: "Động từ" },
      { chinese: "多少", pinyin: "duōshao", vietnamese: "bao nhiêu", wordType: "Đại từ" },
      { chinese: "怎么", pinyin: "zěnme", vietnamese: "thế nào, sao", wordType: "Đại từ" },
      { chinese: "贵", pinyin: "guì", vietnamese: "đắt", wordType: "Tính từ" },
      { chinese: "便宜", pinyin: "piányi", vietnamese: "rẻ", wordType: "Tính từ" },
      { chinese: "块", pinyin: "kuài", vietnamese: "đồng (tệ)", wordType: "Lượng từ" },
      { chinese: "毛", pinyin: "máo", vietnamese: "hào", wordType: "Lượng từ" },
      { chinese: "分", pinyin: "fēn", vietnamese: "xu", wordType: "Lượng từ" },
      { chinese: "给", pinyin: "gěi", vietnamese: "cho", wordType: "Động từ" },
      { chinese: "找", pinyin: "zhǎo", vietnamese: "tìm, trả lại (tiền thừa)", wordType: "Động từ" },
      { chinese: "一共", pinyin: "yígòng", vietnamese: "tổng cộng", wordType: "Phó từ" },
      { chinese: "斤", pinyin: "jīn", vietnamese: "cân (0,5kg)", wordType: "Lượng từ" },
      { chinese: "公斤", pinyin: "gōngjīn", vietnamese: "kilôgam", wordType: "Lượng từ" },
      { chinese: "大概", pinyin: "dàgài", vietnamese: "khoảng, đại khái", wordType: "Phó từ" },
      { chinese: "一点儿", pinyin: "yìdiǎnr", vietnamese: "một chút", wordType: "Lượng từ" },
      { chinese: "有点儿", pinyin: "yǒudiǎnr", vietnamese: "hơi (mang ý không hài lòng)", wordType: "Phó từ" },
    ],
    sentenceTranslation: [
      { vietnameseSentence: "Bây giờ bạn có bao nhiêu tiền?", chineseSentence: "现在你有多少钱？", pinyin: "xiànzài nǐ yǒu duōshao qián?" },
      { vietnameseSentence: "Bộ quần áo này bao nhiêu tiền?", chineseSentence: "这件衣服多少钱？", pinyin: "zhè jiàn yīfu duōshao qián?" },
      { vietnameseSentence: "Anh ấy muốn mua bao nhiêu?", chineseSentence: "他想买多少？", pinyin: "tā xiǎng mǎi duōshao?" },
      { vietnameseSentence: "Hôm nay bạn đến công ty kiểu gì?", chineseSentence: "今天你怎么来公司？", pinyin: "jīntiān nǐ zěnme lái gōngsī?" },
      { vietnameseSentence: "Sao hôm qua cậu không đến nhà tớ?", chineseSentence: "昨天你怎么不来我家？", pinyin: "zuótiān nǐ zěnme bù lái wǒ jiā?" },
      { vietnameseSentence: "Cô ấy cho tôi một quyển sách tiếng Trung.", chineseSentence: "她给我一本中文书。", pinyin: "tā gěi wǒ yì běn zhōngwén shū." },
      { vietnameseSentence: "Anh ấy mua cho tôi rất nhiều hoa quả.", chineseSentence: "他给我买很多水果。", pinyin: "tā gěi wǒ mǎi hěn duō shuǐguǒ." },
      { vietnameseSentence: "Bạn ăn một chút cơm đi.", chineseSentence: "你吃一点儿饭吧。", pinyin: "nǐ chī yìdiǎnr fàn ba." },
      { vietnameseSentence: "Có thể rẻ hơn một chút không?", chineseSentence: "可以便宜一点儿吗？", pinyin: "kěyǐ piányi yìdiǎnr ma?" },
      { vietnameseSentence: "Cái điện thoại này hơi đắt.", chineseSentence: "这个手机有点儿贵。", pinyin: "zhège shǒujī yǒudiǎnr guì." },
      { vietnameseSentence: "Tớ cảm thấy hơi mệt.", chineseSentence: "我觉得有点儿累。", pinyin: "wǒ juéde yǒudiǎnr lèi." },
      { vietnameseSentence: "Dạo này công việc của tôi hơi bận.", chineseSentence: "最近我的工作有点儿忙。", pinyin: "zuìjìn wǒ de gōngzuò yǒudiǎnr máng." },
    ],
    sentence: [
      { correctSentence: "你想买别的吗", pinyin: "nǐ xiǎng mǎi biéde ma", vietnameseMeaning: "Bạn muốn mua cái khác không?" },
      { correctSentence: "我的水果一共多少钱", pinyin: "wǒ de shuǐguǒ yígòng duōshao qián", vietnameseMeaning: "Hoa quả của tôi tổng cộng bao nhiêu tiền?" },
      { correctSentence: "今天的橘子怎么卖", pinyin: "jīntiān de júzi zěnme mài", vietnameseMeaning: "Quýt hôm nay bán thế nào?" },
      { correctSentence: "你在哪儿买水果", pinyin: "nǐ zài nǎr mǎi shuǐguǒ", vietnameseMeaning: "Bạn mua hoa quả ở đâu?" },
      { correctSentence: "老板我给你三十块", pinyin: "lǎobǎn wǒ gěi nǐ sānshí kuài", vietnameseMeaning: "Ông chủ, tôi đưa anh 30 tệ." },
    ],
  },
];
